### ISSUE TITLE
PLUGIN ISSUE

### ISSUE THREAD

**Issue by dhifafaz** [microsoft/TaskWeaver#105]
I try to use the plugin but keep getting this error anyone know what is the cause? 

![image](https://github.com/microsoft/TaskWeaver/assets/54610871/ead041ea-c61b-4a28-9697-592f5771a350)

and this is my config

![image](https://github.com/microsoft/TaskWeaver/assets/54610871/60e3ac95-f91f-433d-b408-af75f7110105)

**Comment by zhangxu0307** [comment]
Hi, @dhifafaz ! Could you sync to the latest code and have a try again? If you still encounter the same issue, please share the logs to us. Thanks.

**Comment by dhifafaz** [comment]
> Hi, @dhifafaz ! Could you sync to the latest code and have a try again? If you still encounter the same issue, please share the logs to us. Thanks.

hai thanks for responding, i figured it out the issue, it was by my fault, im insert the wrong path for code_generator.example_base_path

**Comment by dhifafaz** [comment]
Hai @zhangxu0307 one quick question, i try to add custom plugins that looks like this
![image](https://github.com/microsoft/TaskWeaver/assets/54610871/89e122a2-a1ee-4404-9e16-1a13568e0564)

but it always failed to executed, the response always look like this

```
2024-01-08 17:00:24 - CodeInterpreter talk to CodeInterpreter: The following python code has been executed:
```python
# Attempting to call the agent_profiling_brand plugin again to analyze the brand 'Telkomsel Indonesia'
# According to the instructions, there is no need to import the plugin, and the result variables should be placed on the last line of the code
brand_profiling_result, brand_profiling_description = agent_profiling_brand('Telkomsel Indonesia')

# Output the profiling result and description
(brand_profiling_result, brand_profiling_description)
```


The execution of the generated python code above has failed

During execution, the following messages were logged:
Traceback (most recent call last):

  Cell In[5], line 3
    brand_profiling_result, brand_profiling_description = agent_profiling_brand('Telkomsel Indonesia')

NameError: name 'agent_profiling_brand' is not defined

```

**Comment by zhangxu0307** [comment]
Would you mind sharing your spec yaml and implentation python files to us? So that we can debug locally to see how to solve this issue. Thanks.

**Comment by dhifafaz** [comment]
i think i found the issue, earlier i try to run it on web ui, and now i try to run it from cli, it shows wrong importing files

![image](https://github.com/microsoft/TaskWeaver/assets/54610871/4f100843-c114-4147-9871-3f83fcf5d3f1)

Because my directory is look like this

![image](https://github.com/microsoft/TaskWeaver/assets/54610871/93b38a57-2ce4-4eea-9531-ed9b43792576)

I'm trying to import a module from custom_module dir. I'm a bit confuse about the importing package for making a plugins. Cause i still figure it out from which dir. the plugin will be executed. Sorry...

**Comment by dhifafaz** [comment]
Or i just need to move out the custom_modules dir. outside the project dir. under the TaskWeaver?

**Comment by dhifafaz** [comment]
okay thanks a lot, it finally working the approach that i take is to move out the custom_modules dir. Thank you so much for your help.
