### ISSUE TITLE
POSSIBLE TYPO ON EMBEDDINGS

### ISSUE THREAD

**Issue by dhifafaz** [microsoft/TaskWeaver#107]
I found some typo about embedding, in the documentation mentioned about llm.embedding_api_type that we can use sentence_transformers, below

![image](https://github.com/microsoft/TaskWeaver/assets/54610871/2977df58-86a0-4c38-9327-1cefc40a9c1b)

when i try to configure my config to add my custom embeddings model, the program returns error, that says there is no sentence_transformers embedding. So i trace it and found this

![image](https://github.com/microsoft/TaskWeaver/assets/54610871/e90fabf4-23f0-4d71-91e6-4ae058bd0d28)

In the source code you guys wrote sentence_transformer not sentence_transformers. So which one will be corrected? The docs or the code? Thanks!

**Comment by zhangxu0307** [comment]
Thanks for pointing out this issue. We will fix in this PR (#34).
