### ISSUE TITLE
session.max_internal_chat_round_num doesn't seem to change behaviour

### ISSUE THREAD

**Issue by PipXBT** [microsoft/TaskWeaver#120]
**Describe the bug**

I changed the  doesn't seem to change behaviour to 25 in the config file however I still get error:

"Exception: Internal chat round number exceeds the limit of 10"

**To Reproduce**
Change the number to greater than 10 and let it loop you should find it stops at 10

**Expected behavior**
I was thinking it should loop for 25 times?

**Environment Information (please complete the following information):**
 - OS: [macOS]
 - Python Version 3.11
 - LLM that you're using: GPT-4

**Additional context**

**Comment by zhangxu0307** [comment]
Hi, @PipXBT ! How did you setup the internal max round number? Generally, you need to set `session.max_internal_chat_round_num` in the` taskeaver_config.json` file.

**Comment by PipXBT** [comment]
Didn't work for me there but did here:

https://github.com/microsoft/TaskWeaver/blob/main/taskweaver/session/session.py

![Screenshot_2024-01-14_at_1 24 49_am](https://github.com/microsoft/TaskWeaver/assets/84630076/67f7e643-a837-453a-baf9-ec815efba297)

**Comment by PipXBT** [comment]
The above worked for me doing > 10 now.
