### ISSUE TITLE
Optimizing Large Dataset Responses in Custom Plugins: Balancing DataFrame and Excel File Outputs Based on Record Count

### ISSUE THREAD

**Issue by Netizine** [microsoft/TaskWeaver#121]
When responding in a custom plugin, the support for the panda data frame is awesome, but is it possible to determine how to reply based on the number of records? For context, we have a custom plugin that retrieves records from a db to answer questions, but if the question was something like "Get all orders in December that were delivered to the UK?" we land up with a scenario where we could be returning 1000's of records. Returning this as text isn't a viable option, so we would like to generate an Excel file and return the link to this file. So, to solve this, we need to return either pd.DataFrame(rows, columns=[.... or a link to the generated Excel file because passing the panda data frame to an LLM isn't a viable option. The returning data type of the plugin needs to be dependent on the number of rows returned. Of course, we could write 2 plugins, but we won't know which one to call until we get the results record count. A user could ask "Get all my orders for December". If there's one order, there is no need to generate an Excel file with 1 record but if there are 100, not only would the response be impractical, but it would also exceed the max token count of most LLMs.

**Comment by liqul** [comment]
Hi @Netizine, if I understand correctly, you want to return the data as text if it is small, or as a link to file if it has many rows, right? However, why not always pass a few sample rows to the LLM and keep the dataset in memory (or on disk if the data is too large)? I didn't get the point why passing raw data to the LLM except that, e.g., you want to use LLM to read all your data to draw insight, which however is not the strength of LLM.

**Comment by Netizine** [comment]
No, as a data table, if it's small, but a link to the data in Excel is above a specific size. Even if I save it locally, I still need somewhere to determine what the response entails. In hindsight, I think I need to determine this in the plugin itself and always return text that either includes the summary or the link and as such, I can return the end result.
