### ISSUE TITLE
How to enable streaming in chainlit example

### ISSUE THREAD

**Issue by NisaarAgharia** [microsoft/TaskWeaver#127]

**Comment by ShilinHe** [comment]
Streaming is by default enabled. You need to pull the latest code and then follow the UI running [example](https://microsoft.github.io/TaskWeaver/docs/usage/webui)


![chrome-capture-2024-1-16](https://github.com/microsoft/TaskWeaver/assets/10590876/2b56643a-4412-471a-a442-999fdbffb149)

**Comment by NisaarAgharia** [comment]
<img width="109" alt="image" src="https://github.com/microsoft/TaskWeaver/assets/22457544/2197f9e9-3065-469d-a160-249bb1d8a2c9">

For me it is showing Running but not streaming intermediate steps. 

is there anything specific that needs to be done to show intermediate steps when they are generated

**Comment by ShilinHe** [comment]
Nothing needs to be configured as long as the code is the latest, can you clear the cache and try again?

**Comment by NisaarAgharia** [comment]
I cloned the repo last week. Have these changes been done recently?

**Comment by ShilinHe** [comment]
Yes, it was updated yesterday. You may pull the latest code to see whether streaming works.

**Comment by NisaarAgharia** [comment]
Thanks a lot , Works like a Charm.
