### ISSUE TITLE
Not working with QWen's qwen-max-longcontext model

### ISSUE THREAD

**Issue by lidh15** [microsoft/TaskWeaver#129]
**Describe the bug**

if we modify the model in qwen example config from `qwen-max` to `qwen-max-longcontext`, it will raise an error saying `response` which is of type generator didn't have attributes `status_code` nor `error`.

**To Reproduce**

modify the model in qwen example config from `qwen-max` to `qwen-max-longcontext`
whatever query, it's not about the contents in my case

**Expected behavior**
A clear and concise description of what you expected to happen. NA if feel not applicable.

I expect it run without raising the error

**Screenshots**

N/A
but I can tell you it is at taskweaver/llm/qwen.py line 86 or nearby

**Environment Information (please complete the following information):**
 - OS: WSL
 - Python Version 3.10
 - LLM that you're using: qwen

**Additional context**

I think it is related to the different return types of the qwen models, maybe need some adaption

**Comment by zhangxu0307** [comment]
Hi, @lidh15 ! Thanks for your point out this problem. We have fixed this issue in #164. 
After bug fix, I had a try on `Qwen-max-longcontext` and it reported the throttling error from the server side. So it could be problem on Qwen API. You can pull the latest code and reproduce this issue to check which kind of error emerged in Qwen API.

**Comment by liqul** [comment]
Close inactive issues.
