### ISSUE TITLE
How to set a plugin (dataset from backend)

### ISSUE THREAD

**Issue by AbhijitManepatil** [microsoft/TaskWeaver#131]
Instated of asking initially pull a data from 'time_series' table from 'sqlite://test.db'
How can I set this (database) in backend when app loads then start directly asking questions.?

**Comment by ShilinHe** [comment]
We would suggest wrap around the taskweaver and automatically send a request (e.g., pull the data) to Taskweaver on behalf of human when starting the services.

**Comment by Haxeebraja** [comment]
> We would suggest wrap around the taskweaver and automatically send a request (e.g., pull the data) to Taskweaver on behalf of human when starting the services.

Can you please elaborate how to set this up in code?
I want to work with one csv file that can be accessed from plugins and stays in memory in the session.

**Comment by xsa-dev** [comment]
### CodeInterpreter File Handling

To enable CodeInterpreter to access data, I supplied the complete file path, and the file was successfully read and processed. It is important to emphasize that the file must be reachable by the user executing TaskWeave and must have the necessary read permissions.

### Plugins in the Application

1. **sql_pull_data Plugin**
   - [Source Code](https://github.com/microsoft/TaskWeaver/blob/55d42c418a6a977dec3645abb151f2c45f4bb8e9/project/plugins/sql_pull_data.py#L46)
   - The path to the SQLite database is determined from an environment variable.
   ![sql_pull_data Plugin](https://github.com/microsoft/TaskWeaver/assets/16959353/2f4062ed-1fa7-4581-bc5e-0757e9c4179e)

2. **anomaly_detection Plugin**
   - [Source Code](https://github.com/microsoft/TaskWeaver/blob/55d42c418a6a977dec3645abb151f2c45f4bb8e9/project/plugins/anomaly_detection.py#L44)
   - The file is incorporated into the context.
   ![anomaly_detection Plugin](https://github.com/microsoft/TaskWeaver/assets/16959353/d6f801d3-2c25-40a1-99dd-4f7abe7761f1)

Creating a custom plugin might prove more convenient than exploring alternatives. Consider specifying the full file path for CodeInterpreter, as it could enhance control and compatibility.

**Comment by AbhijitManepatil** [comment]
> ### CodeInterpreter File Handling
> To enable CodeInterpreter to access data, I supplied the complete file path, and the file was successfully read and processed. It is important to emphasize that the file must be reachable by the user executing TaskWeave and must have the necessary read permissions.
> 
> ### Plugins in the Application
> 1. **sql_pull_data Plugin**
>    
>    * [Source Code](https://github.com/microsoft/TaskWeaver/blob/55d42c418a6a977dec3645abb151f2c45f4bb8e9/project/plugins/sql_pull_data.py#L46)
>    * The path to the SQLite database is determined from an environment variable.
>      ![sql_pull_data Plugin](https://private-user-images.githubusercontent.com/16959353/301675529-2f4062ed-1fa7-4581-bc5e-0757e9c4179e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4NjgxMzgsIm5iZiI6MTcwNjg2NzgzOCwicGF0aCI6Ii8xNjk1OTM1My8zMDE2NzU1MjktMmY0MDYyZWQtMWZhNy00NTgxLWJjNWUtMDc1N2U5YzQxNzllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDA5NTcxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiNDJiMzY0YmJkMjg2Yzk0MzQ0MDAzOGIxNzBmZjk0ZTc5ZGFiMThkNDA3ZjU2YzAxZmQ2NTFiZmIzZDFmYTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PxksTZZ6xgs67KNaSkFHl9DOoi9tjuziNS34roqzIkQ)
> 2. **anomaly_detection Plugin**
>    
>    * [Source Code](https://github.com/microsoft/TaskWeaver/blob/55d42c418a6a977dec3645abb151f2c45f4bb8e9/project/plugins/anomaly_detection.py#L44)
>    * The file is incorporated into the context.
>      ![anomaly_detection Plugin](https://private-user-images.githubusercontent.com/16959353/301675136-d6f801d3-2c25-40a1-99dd-4f7abe7761f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4NjgxMzgsIm5iZiI6MTcwNjg2NzgzOCwicGF0aCI6Ii8xNjk1OTM1My8zMDE2NzUxMzYtZDZmODAxZDMtMmMyNS00MGExLTk5ZGQtNGY3YWJlNzc2MWYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDA5NTcxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwZTMxNGYzZTdmOTQ0M2QwNDJjNDIwMDdkZDc5M2NmZmMyNmZjNWM0ODBlY2UyYzg4ZWNkNTUxNzRkYjFmNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BoQrJiYIydXaNG8NYL2hUO2kGc36TUDXf_kKZjbpY9s)
> 
> Creating a custom plugin might prove more convenient than exploring alternatives. Consider specifying the full file path for CodeInterpreter, as it could enhance control and compatibility.

Thanks for the response, looks more promising.

**Comment by NisaarAgharia** [comment]
I have one Query here, 

I have a SQL Db sitting on the Cloud and i am using similar Function to connect to it 
 db = SQLDatabase.from_uri("SQL PATH")
 
 I am Seeing this observation that when the CI calls the Plugin , it takes time to make connection every time. 
 
 I dont want to make connection every time i want to reuse the Connection so that i can reduce latency and not needing to connect to the DB every time the plugin gets called 
 
 Can some one suggest a solution where DB object is only instanciated once and Reused again in the plugins. Hence Reducing Latency

**Comment by liqul** [comment]
> I have one Query here,
> 
> I have a SQL Db sitting on the Cloud and i am using similar Function to connect to it db = SQLDatabase.from_uri("SQL PATH")
> 
> I am Seeing this observation that when the CI calls the Plugin , it takes time to make connection every time.
> 
> I dont want to make connection every time i want to reuse the Connection so that i can reduce latency and not needing to connect to the DB every time the plugin gets called
> 
> Can some one suggest a solution where DB object is only instanciated once and Reused again in the plugins. Hence Reducing Latency

A simple way to achieve this is as follows:
```python
@register_plugin
class SqlPullData(Plugin):
    db = None
    def __call__(self, query: str):
        ...
        if db is None:
            db = SQLDatabase.from_uri(self.config.get("sqlite_db_path"))
```
The connection will be created at the first time calling this plugin and reused in following calls.

**Comment by NisaarAgharia** [comment]
Thanks @liqul ,  One more question : 
Lets say i initialize it once and use it again, 
what if the connection is broken or it is stale. 

what would be a best way to implement above logic while also handling scenarios where connection would be stale or lost?

**Comment by liqul** [comment]
This may be a bit going beyond developing the plugin. It is a common issue for all db access scenarios. I didn't investigate it and you can take a look at langchain's implementation details [here](https://python.langchain.com/docs/expression_language/cookbook/sql_db).
