### ISSUE TITLE
CodeSpace is disabled

### ISSUE THREAD

**Issue by cswangxiaowei** [microsoft/TaskWeaver#133]
May I know why I am disabled from creating a codespace from task weaver github respo? 
Thank you! 
![disabled](https://github.com/microsoft/TaskWeaver/assets/145024452/fdc12bdc-538a-4b42-aa50-315f5671efc9)

**Comment by ShilinHe** [comment]
Hi @cswangxiaowei, could you check any configuration related the codespace? I can see the codespace after switching to my private GitHub account.
![image](https://github.com/microsoft/TaskWeaver/assets/10590876/d8e7438e-8ee3-465a-b7e3-0e995832d37a)

**Comment by cswangxiaowei** [comment]
My code space is still disabled. Besides, may I know how if I can use this format to use qwen's api with baichuan model? I tried but failed: 
{
    "llm.api_type": "qwen",
    "llm.model": "baichuan2-7b-chat-v1", 
    "llm.api_key": "YOUR_API_KEY"
}
p.s. I test this api locally and it works so I think there must be some problem with the code format of using this api. 
Thank you!

**Comment by cswangxiaowei** [comment]
I solved the problem of creating a codespace. Please just review my issue of api format: {
"llm.api_type": "qwen",
"llm.model": "baichuan2-7b-chat-v1",
"llm.api_key": "YOUR_API_KEY"
}
May I know if this one will work?

**Comment by ShilinHe** [comment]
We don't directly support the baichuan model, but you can configure it by using the `litellm` api_type. In `litellm`, you can follow instructions in this [page](https://docs.litellm.ai/docs/providers/vllm) to connect via `vllm` provider, which now supports baichuan2 model.

**Comment by ShilinHe** [comment]
Thanks for sharing the information. For the baichuan model, are you referring to the open-sourced one or the commercial one? Do you have any docs about the Baichuan on QWen? Thanks!

**Comment by cswangxiaowei** [comment]
No problem, I want to use baichuan2-13b-chat-v1, which is free now. https://help.aliyun.com/zh/dashscope/developer-reference/baichuan-metering-and-billing?spm=a2c4g.11186623.0.i10 
[
![baichuan](https://github.com/microsoft/TaskWeaver/assets/145024452/362fd981-00a6-405b-b1d8-7ed168b3926d)
](url)

**Comment by ShilinHe** [comment]
Hi, @cswangxiaowei, the issue was triggered because Baichuan2 on QWen does not support the streaming mode. We therefore add a new config item to it (`"llm.qwen.stream": false`). PR: #140 

However, another issue occurred: the context length of Baichuan2 7B/13B on QWen (not sure why) is 2048 token only, which is not sufficient to accommodate our prompt. Therefore, it will fail.

**Comment by cswangxiaowei** [comment]
Thank you!
