### ISSUE TITLE
what are the main differences between taskweaver and langchain?

### ISSUE THREAD

**Issue by lidh15** [microsoft/TaskWeaver#138]
how do taskweaver different from langchain?

**Comment by liqul** [comment]
In general:

Langchain provides a great set of tools for developing LLM based systems. Developers are typically expected to pick what they need from the repo and write codes or customize prompts to build a system. 

Taskweaver is more for developing an conversational assistant for data analysis or other automation tasks. Developers are typically expected to add only plugins and examples to make it work, but changing its code or internal prompts.

**Comment by lidh15** [comment]
> In general:
> 
> Langchain provides a great set of tools for developing LLM based systems. Developers are typically expected to pick what they need from the repo and write codes or customize prompts to build a system. 
> 
> Taskweaver is more for developing an conversational assistant for data analysis or other automation tasks. Developers are typically expected to add only plugins and examples to make it work, but changing its code or internal prompts.

thank you!

**Comment by adrianostr** [comment]
@liqul "but changing its code or internal prompts" what do you mean by this?

**Comment by adrianog** [comment]
@liqul "but changing its code or internal prompts" what do you mean by this?
