### ISSUE TITLE
Great package and want to explore. Is that possible to work in VS code instead of console?

### ISSUE THREAD

**Issue by mraguth** [microsoft/TaskWeaver#14]
I use Anaconda and I like to work in VS code. Is that possible?

Thank you and love to explore this package.

**Comment by HenryAllen04** [comment]
I've been running it in VS-code, then you control it inside the terminal folder in VS-code

**Comment by ShilinHe** [comment]
As @HenryAllen04 suggested, you can start the program in the terminal of VS code. The user experience should be same as other terminals. Feel free to reopen the issue if you could not figure it out.
