### ISSUE TITLE
docker use chainlit run app.py have a error:Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### ISSUE THREAD

**Issue by xs818818** [microsoft/TaskWeaver#141]
**Describe the bug**

**To Reproduce**
1. Start the service
2. Type the user query "xxx"
3. Wait for the response
4. Type the user query "yyy"

**Expected behavior**
A clear and concise description of what you expected to happen. NA if feel not applicable.

**Screenshots**

**Environment Information (please complete the following information):**
 - OS: [e.g. Linux, Windows, WSL]
 - Python Version [e.g. 3.10, 3.11]
 - LLM that you're using: [e.g., GPT-4]
 - Other Configurations except the LLM api/key related: [e.g., code_verification: true]

**Additional context**

**Comment by liqul** [comment]
Close inactive issues.
