### ISSUE TITLE
Unable to connect to Azure OpenAI

### ISSUE THREAD

**Issue by mussteven** [microsoft/TaskWeaver#146]
I'm having trouble running the CLI Tool as I keep getting OpenAI API request failed to connect. I'm on azure open ai and here's how I set up my config.json: {
  "llm.api_base":"xxx",
  "llm.api_key":"xxx",
  "llm.api_type":"azure",
  "llm.auth_mode":"api-key",
  "llm.model":"gpt-4-32k",
  "llm.api_version": "2023-03-15-preview",
  "llm.response_format": "null"
} Anyone encountered this before?

**Comment by liqul** [comment]
@mussteven Hi, could you change `response_format` to `null`, not wrapped with `"`.

**Comment by nick917** [comment]
https://microsoft.github.io/TaskWeaver/docs/llms/aoai
Does not work following it. Also tried adding "llm.api_version": "2023-08-01-preview", but no luck.

**Comment by liqul** [comment]
Close inactive issues.
