### ISSUE TITLE
Errors with fastchat deployed model

### ISSUE THREAD

**Issue by ruifengma** [microsoft/TaskWeaver#153]
**Describe the problem**
I deployed a Qwen model with fastchat and it worked with following calling script
```
from openai import OpenAI

client = OpenAI(
  api_key = "Null",
  base_url = "http://10.77.170.169:8097/v1"
)

messages = [{"role": "user", "content": "hello, what can you do?"}]
response = client.chat.completions.create(
    model="Qwen-14B-Chat",
    messages=messages,
    temperature=0.7,
)
print(response.choices[0].message.content)
```
and my config file looks like this 
```
{
    "llm.api_type":"openai",
    "llm.api_base": "http://10.77.170.169:8097/v1",
    "llm.api_key": "Null",
    "llm.model": "Qwen-14B-Chat",
    "llm.response_format": "json_object"
}
```
Then I start the process with 

`python -m taskweaver -p ./project/`

It gives me the errors
```
 TaskWeaver ▶  I am TaskWeaver, an AI assistant. To get started, could you please enter your request?
    Human   ▶  hello
Exception in thread Thread-3 (base_stream_puller):=>
Traceback (most recent call last):
  File "/data/mrx/agent/TaskWeaver/taskweaver-src/taskweaver/llm/openai.py", line 163, in chat_completion
    res: Any = self.client.chat.completions.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/taskweaver/lib/python3.11/site-packages/openai/_utils/_utils.py", line 271, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/taskweaver/lib/python3.11/site-packages/openai/resources/chat/completions.py", line 648, in create
    return self._post(
           ^^^^^^^^^^^
  File "/root/miniconda3/envs/taskweaver/lib/python3.11/site-packages/openai/_base_client.py", line 1167, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/taskweaver/lib/python3.11/site-packages/openai/_base_client.py", line 856, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/taskweaver/lib/python3.11/site-packages/openai/_base_client.py", line 947, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.BadRequestError: Error code: 400 - {'object': 'error', 'message': "This model's maximum context length is 2048 tokens. However, your messages resulted in 2280 tokens. Please reduce the length of the messages.", 'code': 40303}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/taskweaver/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/root/miniconda3/envs/taskweaver/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/data/mrx/agent/TaskWeaver/taskweaver-src/taskweaver/llm/__init__.py", line 162, in base_stream_puller
    for msg in stream:
  File "/data/mrx/agent/TaskWeaver/taskweaver-src/taskweaver/llm/openai.py", line 218, in chat_completion
    raise Exception(f"OpenAI API request was invalid: {e}")
Exception: OpenAI API request was invalid: Error code: 400 - {'object': 'error', 'message': "This model's maximum context length is 2048 tokens. However, your messages resulted in 2280 tokens. Please reduce the length of the messages.", 'code': 40303}
```
My env infos:
OS: CentOS 7
Python: 3.11
Openai: 1.8.0
Taskweaver: the latest

**Comment by liqul** [comment]
@ruifengma Hi, as shown in the error logs "This model's maximum context length is 2048 tokens. However, your messages resulted in 2280 tokens. Please reduce the length of the messages.". So a model with larger context length should be provided.

**Comment by ruifengma** [comment]
@liqul Thanks for the reply, I notice the error message as well. But it's wired for that evenif I just say "Hello", the error message is just the same as above.

**Comment by liqul** [comment]
> @liqul Thanks for the reply, I notice the error message as well. But it's wired for that evenif I just say "Hello", the error message is just the same as above.

Although your request is only "hello", in the background, TaskWeaver needs to compose a prompt, putting this request inside it. So, it is not because of the length of the request, but the length of the whole prompt which exceeds the 2000 token limit.

**Comment by ruifengma** [comment]
@liqul How does TaskWeaver compose a prompt? By hardcoded intergration? or generate with LLM? The error message immediately shows up when I press the enter button. Unless the system default prompt is over 2000 token, otherwise I don't think my local Qwen can respond 2000 token in less than 0.2 seconds.

**Comment by liqul** [comment]
> @liqul How does TaskWeaver compose a prompt? By hardcoded intergration? or generate with LLM? The error message immediately shows up when I press the enter button. Unless the system default prompt is over 2000 token, otherwise I don't think my local Qwen can respond 2000 token in less than 0.2 seconds.

Yes, the planner's prompt is around 2K.

**Comment by ruifengma** [comment]
> > @liqul How does TaskWeaver compose a prompt? By hardcoded intergration? or generate with LLM? The error message immediately shows up when I press the enter button. Unless the system default prompt is over 2000 token, otherwise I don't think my local Qwen can respond 2000 token in less than 0.2 seconds.
> 
> Yes, the planner's prompt is around 2K.

Thanks @liqul , that makes sense to me now. I also played with GPT-3.5-Turbo-1106 and similar error message came out after 4 or 5 round (num of token over 4096 or something). Then it seems that some normal models is not really capable of playing with TaskWeaver. Except GPT-4 serise, any open source model do you recommend to play with TaskWeaver well? Thanks

**Comment by liqul** [comment]
> > > @liqul How does TaskWeaver compose a prompt? By hardcoded intergration? or generate with LLM? The error message immediately shows up when I press the enter button. Unless the system default prompt is over 2000 token, otherwise I don't think my local Qwen can respond 2000 token in less than 0.2 seconds.
> > 
> > 
> > Yes, the planner's prompt is around 2K.
> 
> Thanks @liqul , that makes sense to me now. I also played with GPT-3.5-Turbo-1106 and similar error message came out after 4 or 5 round (num of token over 4096 or something). Then it seems that some normal models is not really capable of playing with TaskWeaver. Except GPT-4 serise, any open source model do you recommend to play with TaskWeaver well? Thanks

Indeed, the agent requires quite lengthy context window in order to put all sorts of information in the prompt. We have two configurations `planner.prompt_compression` and `code_generator.prompt_compression` as shown [here](https://microsoft.github.io/TaskWeaver/docs/configurations) to summarize the chat rounds in chat history. You can probably 
 enable them for a try.
