### ISSUE TITLE
Paper summary plugin not working

### ISSUE THREAD

**Issue by madtank** [microsoft/TaskWeaver#161]
Describe the bug
The paper summary plugin is not working because there are many references to "summarize_paper" instead of "paper_summary". The name of the file and the class name also need to be changed to PaperSummaryPlugin.

Also needed to install langchain and pypdf for to work.

To Reproduce

Start the service
Type the user query "summarize this pdf
Wait for the response
Expected behavior
Use the plugin.

Screenshots
NA

Environment Information

OS: macOS
Python Version: 3.11
LLM that you're using: Web and CLI versions
Other Configurations except the LLM api/key related: NA
Additional context
It seems to be a glitch with the way that the plugin is written. Other people have reported this in Discord as well and it seemed to work for me after changing the references from "summarize paper" to "paper summary".

**Comment by zhangxu0307** [comment]
Thanks for your reminder. Just fixed this issue in #162 .
