### ISSUE TITLE
possible bug: taskweaver_eval.py

### ISSUE THREAD

**Issue by gabscarlett** [microsoft/TaskWeaver#166]
I tried to run the auto evaluation for a single case.

On line 7: "from taskweaver.module.event_emitter import SessionEventHandler"
taskweaver is being called when no such module has been imported.

I get the error: "ModuleNotFoundError: No module named 'taskweaver'"

And there is no module called taskweaver in the pycache, so I cannot import it.

Thanks,

Gab

**Comment by zhangxu0307** [comment]
Thanks for pointing out this issue. We have fixed it in #169 .

**Comment by liqul** [comment]
Solution provided.
