### ISSUE TITLE
Exception: Internal chat round number exceeds the limit of 10

### ISSUE THREAD

**Issue by bibop** [microsoft/TaskWeaver#17]
How do I overcome this problem?

Thanks for the help and keep up the fantastic work!!
Bibop

**Comment by zhangxu0307** [comment]
Hi, @bibop! This problem arises from an inherent constraint on the number of rounds between the Planner and Code Interpreter. This limitation is intentionally implemented to prevent prolonged interactions between both roles.
If you want to increase this limit, you will need to modify the code [here](https://github.com/microsoft/TaskWeaver/blob/3a18ac3309d712efc52ee5a8c370505d182dcb45/taskweaver/session/session.py#L64C1-L65C1) to extend the imposed restriction. Thanks.

**Comment by benjamin-mogensen** [comment]
@zhangxu0307 could this be moved to configuration file so code does not have to be modified ? :)
