### ISSUE TITLE
De-dup the LLM settings configuration required in both taskweaver_config.json and the plugin YAML file

### ISSUE THREAD

**Issue by shantanuv** [microsoft/TaskWeaver#171]
Is there any way to avoid duplication of LLM settings (to be provided in both `taskweaver_config.json` as well as the `plugin YAML file`)? Or this is intentional so that we could use different LLMs for the plugins if required? Maybe there is a way through the PluginContext to get a copy of configuration elements from `taskweaver_config.json`, I'm not sure. 

**Workaround**
For now, I added a custom class and using multiple inheritance for the plugins I'm trying to create.

Thanks

**Comment by liqul** [comment]
@shantanuv You are right that, sometimes, the LLM configurations can be duplicated. In our architectural design, we consider the plugins run in a different environment other than the main process. Although they live in the same environment today, we are planning moving the code executor into a safer place such as a sandbox. In that case, the plugins will be unable to read the configruation file of the project. That is the main reason we are keeping separate configurations.

**Comment by shantanuv** [comment]
@liqul - Understood. Thanks for the explanation.
