### ISSUE TITLE
The App is not running 

### ISSUE THREAD

**Issue by SurajGThakkar** [microsoft/TaskWeaver#176]
When running the code "Chainlit run app.py" running into an error. 
Please refer to the error message below. 
![image](https://github.com/microsoft/TaskWeaver/assets/135530540/80d0e685-df6a-4821-9efa-f690a35dd844)

**Comment by ShilinHe** [comment]
Hi @SurajGThakkar, can you provide more information about your env? especially what version of `chainlit` you were using.

**Comment by SurajGThakkar** [comment]
Hello Shilinhe, 
Appreciate the quick response. 
The chainlit version I was using is 1.0.100. I got this from https://microsoft.github.io/TaskWeaver/docs/usage/webui/. 
I am using miniconda for the environment with the python version being 3.11.7.

**Comment by liqul** [comment]
close inactive issues
