### ISSUE TITLE
prompt is too long

### ISSUE THREAD

**Issue by ningpengtao-coder** [microsoft/TaskWeaver#181]
The prompt is too long, 8000+. The local model cannot handle such a long prompt. Can you compress it?

**Comment by liqul** [comment]
Could you provide more details? which prompt? after how many rounds?

**Comment by ningpengtao-coder** [comment]
@liqul taskweaver/planner/planner_prompt.yaml

**Comment by liqul** [comment]
At the first round, the planner's prompt is typically ~3k. We had a prompt summarization feature to reduce the prompt size detailed here (https://microsoft.github.io/TaskWeaver/docs/compression). You can have a try.

**Comment by liqul** [comment]
Close inactive issues.
