### ISSUE TITLE
AutoGen Integration

### ISSUE THREAD

**Issue by MrCandle** [microsoft/TaskWeaver#188]
**Is your feature request related to a problem? Please describe.**
According to the original TaskWeaver paper and this diagram:
<img width="826" alt="image" src="https://github.com/microsoft/TaskWeaver/assets/15315936/e50ddbfa-6cec-47c9-ae6e-3edb4e09bad1">
It should be possible to use TaskWeaver as an agent inside an AutoGen solution or as a plugin inside TaskWeaver
Is there any documentation on how to achieve that?

**Describe the solution you'd like**
A document or example explaining how to integrate AutoGen and TaskWeaver

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by liqul** [comment]
@MrCandle It is not possible to use TaskWeaver as an agent "inside" AutoGen. In our tech report, the idea is that TaskWeaver can act as an agent talking to other agents (e.g., implemented using AutoGen). We notice that, in AutoGen, different "agents" talk to each other within a single process. That's why TaskWeaver cannot be part of any running process.

**Comment by MrCandle** [comment]
@liqul thanks for your answer!
That makes sense, TaskWeaver cannot run "inside" AutoGen.
Is there an example showing how a TaskWeaver agent can talk to other agents running on AutoGen?
I understand they should be running on different processes, so what's the recommended approach on communicating with each other?

**Comment by kripper** [comment]
> @MrCandle It is not possible to use TaskWeaver as an agent "inside" AutoGen. In our tech report, the idea is that TaskWeaver can act as an agent talking to other agents (e.g., implemented using AutoGen). We notice that, in AutoGen, different "agents" talk to each other within a single process. That's why TaskWeaver cannot be part of any running process.

Can you please explain more in detail? Or maybe point to the mentioned tech report?

**Comment by liqul** [comment]
close inactive issues
