### ISSUE TITLE
prompt is too long

### ISSUE THREAD

**Issue by Coderpsh** [microsoft/TaskWeaver#189]
Examples are finally loaded in prompt to request LLM. If there are too many examples, the prompt will be too long. Do you have any plans to solve it?

**Comment by liqul** [comment]
An example is a comprehensive way to teach the LLM for a certain task. In our current implementation, we add 1~2 examples by default to teach the model on correct output format. So, if your examples are used to teach very fine-grained features, there is probably no better way to achieve that than adding examples. But if your requirement is to add some guidance (e.g., paragraphs on how to get a certain request done) you may want to checkout the [experience](https://microsoft.github.io/TaskWeaver/docs/experience) feature which is more efficient in terms of prompt tokens. 

Let us know more details if this cannot help in your specific scenario.

**Comment by liqul** [comment]
close inactive issues
