### ISSUE TITLE
Unable to "/save" experience using the library

### ISSUE THREAD

**Issue by ysid27** [microsoft/TaskWeaver#193]
**Describe the bug**
I am sending "/save" command/message to Taskweaver to make it remember an [experience](https://microsoft.github.io/TaskWeaver/docs/experience#example). Taskweaver is failing at doing that.

**To Reproduce**
1. Run Taskweaver by importing as a library
2. After a couple of messages, send the "/save" command/message i.e., `session.send_message("/save")`
3. Wait for the response
4. `{'id': 'round-20240205-472936-424d5z34', 'user_query': '/save', 'state': 'failed', 'post_list': [{'id': 'post-20240205-472936-e97ght638', 'message': '/save', 'send_from': 'User', 'send_to': 'Planner', 'attachment_list': []}]}`

**Expected behavior**
I expect it to save the experience the way it does when run from Terminal

**Environment Information:**
 - OS: Windows
 - Python Version: 3.11.5
 - LLM that you're using: Llama

**Comment by zhangxu0307** [comment]
Hi, @ysid27 ! Did you use `session.send_message("/save")` to save the experience? Actually, all commands starting with` / `only support console chat and not through library usage or Chainlit UI.

**Comment by ysid27** [comment]
Hi @zhangxu0307 ! I am using `session.send_message("/save")` through library. If `session.send_message("/save")` is not the way to save an experience through library, what is the way? Thanks!

**Comment by zhangxu0307** [comment]
So far, we only support user to use `/save` in the console chat ([chat in command line](https://microsoft.github.io/TaskWeaver/docs/quickstart)).

**Comment by ysid27** [comment]
Oh no! Are there plans to extend this feature to library?

**Comment by zhangxu0307** [comment]
A workaround method is trying to use the following code to save chat histroy directly:
`session.memory.save_experience(exp_dir=session.config.experience_dir)`
If it works, you will see a raw exp file saved in your` expereince` dir.
