### ISSUE TITLE
New planner_example does not Work!

### ISSUE THREAD

**Issue by bianheshan** [microsoft/TaskWeaver#198]
**Describe the bug**
1 When I add a new Planner_Example , it does not refered!
2 if using chinese create the planner_example.yaml , it convert chinese to unicode string

**Some doubts**
1 In the planner_prompt.yaml
# About multiple conversations
  - There could be multiple Conversations in the chat history
  - Each Conversation starts with the user query "Let's start a new conversation!".
  - You should not refer to any information from previous Conversations that are independent of the current Conversation.
  **- You should not refer to any information from previous Conversations that are independent of the current Conversation.**
  The chat history contains the planner_example, and this sentence will result in the planner_example not being used.
  
  2   in translator.py file
  structured_llm_text = json.dumps({"response": structured_llm})
  this code will convert chinese to unicode string 
  it should be 
   **structured_llm_text = json.dumps({"response": structured_llm},ensure_ascii=False)**

**Comment by zhangxu0307** [comment]
Hi, @bianheshan ! The planner examples only serve as illustrations of the conversation flow between the user, planner, and code interpreter. To prevent the example conversations from disrupting the current session, we have included [this line](https://github.com/microsoft/TaskWeaver/issues/198#:~:text=%2D%20You%20should%20not%20refer%20to%20any%20information%20from%20previous%20Conversations%20that%20are%20independent%20of%20the%20current%20Conversation.) in the prompt.  If you would like to incorporate your own domain knowledge into your task, you can refer to [experience](https://microsoft.github.io/TaskWeaver/docs/experience/).
