### ISSUE TITLE
Beautiful Repo! AI at its finest ! (Enchancement) pydantic support for plugins

### ISSUE THREAD

**Issue by saakethch** [microsoft/TaskWeaver#2]
Could we have pydantic support for a plugin to support custom object types?
returns:
  - name: df
    type: DataFrame
    description: >-
      This DataFrame extends the input DataFrame with a newly-added column
      "Is_Anomaly" containing the anomaly detection result.
  - name: description
    type: str
    description: This is a string describing the anomaly detection results.

**Comment by ShilinHe** [comment]
Thanks for the suggestion. We will try to support it in the future!
