### ISSUE TITLE
Provide a standard way to register a cached dataframe

### ISSUE THREAD

**Issue by Netizine** [microsoft/TaskWeaver#200]
Lets say you have a plugin that retrieves data based on the inputs but the result is 365 records.
Then further down the line you have a graph plugin. This plugin needs those records but also additional data collected from another plugin. It simply wouldn't make sense to pass it to the LLM as you would suffer not only performance degradation, but bankruptcies from the tokens used. ;-)

**Describe the solution you'd like**
A way to set a cache of either in memory or a distributed cache. The plugin that retries the data can still send the top 2 lines so the LLM understands the structure. The idea been the plan could decide if the LLM requires the dataset or only a reference in each subsequent plan. 

**Describe alternatives you've considered**
Anything that could allow us to have more well described plans so that prompts can be better understood.

**Comment by liqul** [comment]
@Netizine I don't think we need this cache here as the code execution in TaskWeaver is stateful. Let's say you first ask TaskWeaver to pull data from a db. The generated code may look like follows:

```python
df = data_pull(query="select * from data_table")
df
```
This will get the data and display a few sample lines.

Then, you want to use another plugin to process the data, and the generated code looks like:

```python
processed_df = plugin(df)
processed_df
```
Imagine that all the process happen in a Python Jupyter environment across different cells.

So the feature of stateful execution make it convinient to transfer data between plugins without additional cost like embedding all the data in the prompt.

**Comment by liqul** [comment]
close inactive issues
