### ISSUE TITLE
Can I have configuration seperate from plugin definition?

### ISSUE THREAD

**Issue by hv10** [microsoft/TaskWeaver#205]
I am currently trying to integrate the use of TaskWeaver into some data querying tasks I have.
For this I am, among others, building a small plugin which connects to a DB (in my case a HANA SQL db).
When doing so the plugin gets run in an isolated environment (good) and gets the configuration from the plugin definition YAML (also good). The plugin - in general - works nicely.

The issue: I want to share this tool with colleagues, we all have different accounts for the DB. I would like the configuration to be specific to each user but sharing a common GitHub - TaskWeaver Project, to facilitate exchange of code and experiences.
Currently a configuration is only given to  the plugin when defined in the specific configurations array in the plugin definition YAML, it does not seem like adding that configuration through the environment / extra config files is supported, as the code is run within a temporary folder, therefore not having environment files.

**Describe the solution you'd like**
Optimally I could either have a .env file, or .yaml file or a folder of such files to configure the user specific values.

**Describe alternatives you've considered**
Alternatively, allowing for extension with custom fields in the `taskweaver_config.json` could work as well, if those keys would be somehow given through to the plugins (in the `self.config` attribute).

Any guidance on how to do this would be really nice, I could even implement it myself if it is sensible to do so.
I just do not know where to start within the projects code.

Thanks.

**Comment by liqul** [comment]
Hi @hv10, if I understand correctly, you want to build a service based on TaskWeaver where different users may have individual configurations like the user_name and passwd. If this is the case, we do have an approach for this scenario which is now supported if you are using TaskWeaver as a library as decribed in https://microsoft.github.io/TaskWeaver/docs/usage/library/. 

After you get the `session` instance, you can call the method `update_session_var` in the [code](https://github.com/microsoft/TaskWeaver/blob/0b647eb63b0892fc89ed569803d04daca77b66ed/taskweaver/session/session.py#L101C9-L101C27). You can pass a dictionary into this session when necessary. These session variables can then be obtained in the plugin implementation by calling 

```
val = self.ctx.get_session_var(variable_name="key", default=None)
```

We didn't expose this interface to our frontend currently. So, if you want to enable it, you need to build your own wrapper above TaskWeaver so that you can get the information from the current user of the session and then call that method to update the session variables.

Please let us know if this can help in your scenario.

**Comment by bdleavitt** [comment]
+1 for this request. 

I want to be able to use plugins to call external APIs to perform different actions, but it's not clear the best way to store endpoints and secrets such that it can be accessed (perhaps as environment variables) during run execution. 

Custom values accessible from taskweaver_config.json or a .env file would be ideal in my opinion.

**Comment by liqul** [comment]
We intentionally separated the configurations for the main process (in taskweaver_config.json) and the those for the plugins (in the plugin_name.yaml). If the plugin configurations are static, you can just put them into the yaml file. If not, like different users have different configurations, you can try the approach in my previous post. The key point is there need to be someway to map the user to her configurations which is unknown to taskweaver.

**Comment by hv10** [comment]
Thanks @liqul for the answer.

My use case probably calls for less of an involved solution.
I do not want to connect / differentiate multiple users using the same instance of TaskWeaver.
Each user will themselves run their instance of TaskWeaver locally, I just want them to be able to share the underlying code for plugins / etc.
Meaning that the plugin .yaml files will be shared as well - in this case via git - therefore no secrets can be allowed within the configurations section of the yaml.

Building a new interface (using the library approach) is probably a bit out of scope, I'll see if I can figure something out over the next days.

**Comment by bdleavitt** [comment]
> We intentionally separated the configurations for the main process (in taskweaver_config.json) and the those for the plugins (in the plugin_name.yaml). If the plugin configurations are static, you can just put them into the yaml file. If not, like different users have different configurations, you can try the approach in my previous post. The key point is there need to be someway to map the user to her configurations which is unknown to taskweaver.

For me it is not so much about mapping or doing user access management as it about keeping secrets out of the my version control process. 

 the plugin YAML files are absolutely things that need to be versioned and are needed for the plugins to function. So I would love to perhaps reference a custom variable from the taskweaver_config or a .env or something in my plugin YAML file. This would have the added benefit of working in the UI, terminal, or as a library.

**Comment by liqul** [comment]
@bdleavitt @hv10 In this case, you can configure the env variables and read them within the plugin's implementation. Currently, we share the parent process's env variables with the execution environment.
