### ISSUE TITLE
Contributors' Setup

### ISSUE THREAD

**Issue by joshkyh** [microsoft/TaskWeaver#21]
**Describe the solution you'd like**
I was trying to set up the environment for TaskWeaver contributions and think the following two aspects could help:

1. Having a .devcontainer (e.g., https://github.com/microsoft/autogen/tree/main/.devcontainer) so that the contributors could quickly reproduce the environment.
2. Maybe we are missing the `.linters` folder in this repo? I wasn't able to run `pre-commit run --all-files` successfully, but it might be due to me setting it up wrong.

<img width="1365" alt="image" src="https://github.com/microsoft/TaskWeaver/assets/14764966/f50af8ca-5d0b-459a-8f80-a473ed71f5ee">

**Comment by liqul** [comment]
@joshkyh Thanks for the suggestions. Will get those prepared.

**Comment by joshkyh** [comment]
Thanks!
