### ISSUE TITLE
How to tell TaskWeaver to generate, validate and save the code to a file, without executing it?

### ISSUE THREAD

**Issue by kripper** [microsoft/TaskWeaver#224]
**Question**
How to tell TaskWeaver to generate, validate and save the code to a file, without exeuting it?

**Describe the solution you'd like**
Some command or configuration to specify the output filename.

**Describe alternatives you've considered**
After failed execution, I have managed to say somehting like `write the code to file 'output.py'`.

**Additional context**
I'm testing gemini-pro. Maybe the prompts doesn't work exactly the same.

**Comment by liqul** [comment]
Currently, we don't support saving the code to files instead of running it. Any more context on why you need to code but don't want to run it? In that case, why not ask the model to directly generate the code?

**Comment by kripper** [comment]
### Particular use case
Generated code was not working so I wanted to try to fix manually.

### General use case
I would like to ask TW to generate, validate and save code to a file (test.py), test it outside TW (user input doesn't work inside TW) and then provide TW with feedback to enhance the code incrementally.

**Comment by liqul** [comment]
> I would like to:
> 
> 1. Ask TW to generate, validate and save code to a file (test.py).
> 2. Test this code outside TW and then provide TW with feedback to enhance the code incrementally.
> 
> Asking TW to write the code to a file didn't work, but maybe this is because I'm using gemini-pro.

This is not due to the model. We don't support this functionality now. The scenario you described sounds more like a pure code generation task.

**Comment by liqul** [comment]
**close inactive issues**
