### ISSUE TITLE
add a parameter to control whether to refine the plan

### ISSUE THREAD

**Issue by BarryRun** [microsoft/TaskWeaver#226]
**Is your feature request related to a problem? Please describe.**
Some tasks are easy and can usually be finished in 1 or 2 steps. In this case, a refining process is unnecessary and calling LLMs may waste a lot of time (especially with large model).

**Describe the solution you'd like**
Add a parameter like disable_refine_plan which force the TaskWeaver not to refine the plan.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by zhangxu0307** [comment]
Hi, @BarryRun! We suggest you using `planner.skip_planning` to enable the simpliest version of Planner, only including sending request to CodeInterpreter and reporting reuslts to user. If you need to customized your planner prompt, you can modify the [dummy_plan.json](https://github.com/microsoft/TaskWeaver/blob/main/taskweaver/planner/dummy_plan.json). More deatils can be found in [planner doc](https://github.com/microsoft/TaskWeaver/blob/main/website/docs/planner.md).

**Comment by BarryRun** [comment]
Thanks for your reply @zhangxu0307! If I don't want to skip the planning but disable the plan refining, what should I do? Hopping for your replay.

**Comment by zhangxu0307** [comment]
If your task is simple and can be completed in a few steps, the Code Interpreter can take responsibility for creating a basic plan in its `thoughts` and generating the corresponding code. This means that you can use the `planner.skip_planning` directly.
