### ISSUE TITLE
sql_pull_data plugin is throwing NameError: name 'sql_pull_data' is not defined for gemini-pro 

### ISSUE THREAD

**Issue by rrimmana** [microsoft/TaskWeaver#229]
**Describe the bug**
Though code interpreter is generating the code but we see NameError: name 'sql_pull_data' is not defined for gemini-pro llm.
Is this supported for gemini-pro model?. 
Does Taskweaver support function calling 
https://cloud.google.com/vertex-ai/generative-ai/docs/multimodal/function-calling
Please help in resolving above issue.
**To Reproduce**
1. Enabled the sql_data_pull plugin and ask a question. Even its same in UI
2. See error stack below.
=========================================================
 _____         _     _       __
|_   _|_ _ ___| | _ | |     / /__  ____ __   _____  _____
  | |/ _` / __| |/ /| | /| / / _ \/ __ `/ | / / _ \/ ___/
  | | (_| \__ \   < | |/ |/ /  __/ /_/ /| |/ /  __/ /
  |_|\__,_|___/_|\_\|__/|__/\___/\__,_/ |___/\___/_/
=========================================================
 TaskWeaver ▶  I am TaskWeaver, an AI assistant. To get started, could you please enter your request?
    Human   ▶  pull data from time_series table in database
 ╭───< Planner >
 ├─► [init_plan]
 │   1. ask the user to provide the database name
 │   2. ask the user to provide the query
 │   3. instruct CodeInterpreter to pull data from the database
 │   4. report the result to the user <interactively depends on 3>
 ├─► [plan]
 │   1. ask the user to provide the database name
 │   2. ask the user to provide the query
 │   3. instruct CodeInterpreter to pull data from the database
 │   4. report the result to the user
 ├─► [current_plan_step] 1. ask the user to provide the database name
 ├──● What is the name of the database?
 ╰──● sending message to User
 TaskWeaver ▶  What is the name of the database?
    Human   ▶  C:\Taskweaver\TaskWeaver\project\sample_data\anomaly_detection.db
 ╭───< Planner >
 ├─► [init_plan]
 │   1. ask the user to provide the database name
 │   2. ask the user to provide the query
 │   3. instruct CodeInterpreter to pull data from the database
 │   4. report the result to the user <interactively depends on 3>
 ├─► [plan]
 │   1. ask the user to provide the database name
 │   2. ask the user to provide the query
 │   3. instruct CodeInterpreter to pull data from the database
 │   4. report the result to the user
 ├─► [current_plan_step] 2. ask the user to provide the query
 ├──● What is the query to pull data from the database?
 ╰──● sending message to User
 TaskWeaver ▶  What is the query to pull data from the database?
    Human   ▶  select * from time_series
 ╭───< Planner >
 ├─► [init_plan]
 │   1. ask the user to provide the database name
 │   2. ask the user to provide the query
 │   3. instruct CodeInterpreter to pull data from the database
 │   4. report the result to the user <interactively depends on 3>
 ├─► [plan]
 │   1. instruct CodeInterpreter to pull data from the database
 │   2. report the result to the user
 ├─► [current_plan_step] 1. instruct CodeInterpreter to pull data from the database
 ├──● Please pull data from the database using the query: select * from time_series
 ╰──● sending message to CodeInterpreter
 ╭───< CodeInterpreter >
 ├─► [thought] ProgramApe will generate a code snippet to pull data from the database using the query: select * from time_series.
 ├─► [python]
 │   import pandas as pd
 │
 │   query = "select * from time_series"
 │
 │   df, description = sql_pull_data(query)
 │   result = df
 ├─► [verification] NONE
 ├─► [code_error] No code verification is performed.
Plugin sql_pull_data failed to load: Plugin sql_pull_data failed to register: failed to load plugin sql_pull_data cannot import name 'Gemini' from 'langchain.chat_models' (C:\gitlabcode\vertexAI\Taskweaver\TaskWeaver\.venv\Lib\site-packages\langchain\chat_models\__init__.py)
 ├─► [execution_status] FAILURE
 ├─► [execution_result]
 │   The execution of the generated python code above has failed
 │   
 │   During execution, the following messages were logged:
 │   Traceback (most recent call last):
 │
 │     Cell In[1], line 5
 │       df, description = sql_pull_data(query)
 │
 │   NameError: name 'sql_pull_data' is not defined
 │
 │
 ├─► [artifact_paths] []
 ├──● The following python code has been executed:
 │   ```python
 │   import pandas as pd
 │
 │   query = "select * from time_series"
 │
 │   df, description = sql_pull_data(query)
 │   result = df
 │   ```
 │
 │
 │   The execution of the generated python code above has failed
 │
 │   During execution, the following messages were logged:
 │   Traceback (most recent call last):
 │
 │     Cell In[1], line 5
 │       df, description = sql_pull_data(query)
 │
 │   NameError: name 'sql_pull_data' is not defined
 │
 │
 ├─► [revise_message]

**Expected behavior**
A clear and concise description of what you expected to happen. NA if feel not applicable.

**Screenshots**

![image](https://github.com/microsoft/TaskWeaver/assets/24559177/7623533c-1be0-4059-8000-7f50f9e2181d)

**Environment Information (please complete the following information):**
 - OS: Windows
 - Python Version 3.10
 - LLM that you're using: gemini-pro
 

**Additional context**
Will the custom plugins be supported for gemini-pro model.

**Comment by liqul** [comment]
The error message 

```
Plugin sql_pull_data failed to load: Plugin sql_pull_data failed to register: failed to load plugin sql_pull_data cannot import name 'Gemini' from 'langchain.chat_models' (C:\gitlabcode\vertexAI\Taskweaver\TaskWeaver.venv\Lib\site-packages\langchain\chat_models_init_.py)
``` 

is saying that the plugin failed to load successfully. That is why later it is said the name `sql_pull_data` is not recognized.

I guess you want to use gemini-pro for the sql_pull_data plugin, and I can see you have implemented the logic inside the plugin implementation. But the error suggests that you didn't import the correct libraries.

**Comment by rrimmana** [comment]
Thanks  @liqul for quick reply
Didn't notice it. Got it working now with.
![image](https://github.com/microsoft/TaskWeaver/assets/24559177/4ad787fb-6581-48fa-ad2a-4b83cf20507c)
