### ISSUE TITLE
[SUGGEST] Default value of top_p is 0 in OpenAIServiceConfig, which may result BadRequestError 

### ISSUE THREAD

**Issue by BarryRun** [microsoft/TaskWeaver#231]
**Is your feature request related to a problem? Please describe.**
I locally deployed a OpenAI-Compatible server based on Qwen-1.5-Chat model by vllm, then use scripts/llm_api_test.py to test the api. The response gave an error:
```
openai.BadRequestError: Error code: 400 - {'error': {'message': "OpenAIException - Error code: 400 - {'object': 'error', 'message': 'top_p must be in (0, 1], got 0.0.', 'type': 'BadRequestError', 'param': None, 'code': 400}", 'type': None, 'param': None, 'code': 400}}
```
At first,I was unfamiliar with taskweaver, so I thought there was something wrong with the model calling. I tried to rebuild the link based on LiteLLM and vllm. 
I met the same problem two hours later. 
Finally, I found that the default value of top_p in OpenAIServiceConfig is 0.
```
self.top_p = self._get_float("top_p", 0)
```

**Describe the solution you'd like**
Please change the default value of top_p or further improve the document.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by BarryRun** [comment]
And I am confused about how to set the top_p parameter without changing the default value.
I guess maybe I can set a parameter like llm.top_p in taskweaver_config.json？

**Comment by zhangxu0307** [comment]
@BarryRun ! Could you try to set `llm.openai.top_p` as a non-zero value?

**Comment by BarryRun** [comment]
@zhangxu0307 Yes it works, it would be better if you update the document  :)

**Comment by liqul** [comment]
close inactive issues
