### ISSUE TITLE
ModuleNotFoundError: No module named 'plugins'

### ISSUE THREAD

**Issue by GihanMora** [microsoft/TaskWeaver#248]
**Describe the bug**
When I am trying to use built-in plugins sometimes it throws the error "ModuleNotFoundError: No module named 'plugins'" and the code interpreter generates the code on its own without using the plugins.

 Human   ▶  Tell me a joke and draw an ascii art of the last word. please use the plugins
 ╭───< Planner >
 ├─► [init_plan]
 │   1. Tell a joke using the tell_joke plugin
 │   2. Get the last word from the joke
 │   3. Draw an ASCII art of the last word using the ascii_render plugin <sequentially depends on 2>
 │   4. Report the joke and the ASCII art to the user <interactively depends on 3>
 ├─► [plan]
 │   1. Instruct CodeInterpreter to tell a joke using the tell_joke plugin and get the last word from the joke
 │   2. Instruct CodeInterpreter to draw an ASCII art of the last word using the ascii_render plugin
 │   3. Report the joke and the ASCII art to the user
 ├─► [current_plan_step] 1. Instruct CodeInterpreter to tell a joke using the tell_joke plugin and get the last word from the joke
 ├──● Please use the tell_joke plugin to tell a joke and get the last word from the joke
 ╰──● sending message to CodeInterpreter
 ╭───< CodeInterpreter >
 ├─► [thought] ProgramApe will generate a code snippet to tell a joke using the tell_joke plugin and get the last word from the joke using regex.
 ├─► [python]
 │   try:
 │       from plugins import tell_joke, ascii_render
 │   except ImportError:
 │       !pip install plugins
 │       from plugins import tell_joke, ascii_render
 │   
 │   # Tell a joke
 │   joke = tell_joke()
 │   
 │   # Get the last word
 │   last_word = re.findall(r'\b\w+\b', joke)[-1]
 │   
 │   # Draw an ASCII art of the last word
 │   ascii_art = ascii_render(last_word)
 │   
 │   # Report the joke and the ASCII art to the user
 │   joke + f"\n{ascii_art}"
 ├─► [verification] NONE
 ├─► [code_error] No code verification is performed.
 ├─► [execution_status] FAILURE
 ├─► [execution_result]
 │   The execution of the generated python code above has failed
 │   
 │   During execution, the following messages were logged:
 │   Traceback (most recent call last):
 │   
 │     Cell In[3], line 2
 │       from plugins import tell_joke, ascii_render
 │   
 │   ModuleNotFoundError: No module named 'plugins'
 │   
 │   
 │   During handling of the above exception, another exception occurred:
 │   
 │   Traceback (most recent call last):
 │   
 │     Cell In[3], line 5
 │       from plugins import tell_joke, ascii_render
 │   
 │   ModuleNotFoundError: No module named 'plugins'
 │   
 │   ERROR: Could not find a version that satisfies the requirement plugins (from versions: none)
 │   ERROR: No matching distribution found for plugins
 │   
 │   
 ├─► [artifact_paths] []
 ├──● The following python code has been executed:
 │   ```python
 │   try:
 │       from plugins import tell_joke, ascii_render
 │   except ImportError:
 │       !pip install plugins
 │       from plugins import tell_joke, ascii_render
 │   
 │   # Tell a joke
 │   joke = tell_joke()
 │   
 │   # Get the last word
 │   last_word = re.findall(r'\b\w+\b', joke)[-1]
 │   
 │   # Draw an ASCII art of the last word
 │   ascii_art = ascii_render(last_word)
 │   
 │   # Report the joke and the ASCII art to the user
 │   joke + f"\n{ascii_art}"
 │   ```
 │   
 │   
 │   The execution of the generated python code above has failed
 │   
 │   During execution, the following messages were logged:
 │   Traceback (most recent call last):
 │   
 │     Cell In[3], line 2
 │       from plugins import tell_joke, ascii_render
 │   
 │   ModuleNotFoundError: No module named 'plugins'
 │   
 │   
 │   During handling of the above exception, another exception occurred:
 │   
 │   Traceback (most recent call last):
 │   
 │     Cell In[3], line 5
 │       from plugins import tell_joke, ascii_render
 │   
 │   ModuleNotFoundError: No module named 'plugins'
 │   
 │   ERROR: Could not find a version that satisfies the requirement plugins (from versions: none)
 │   ERROR: No matching distribution found for plugins
 │   
 │   

**To Reproduce**
1. Start the service
2. Type the user query "Tell me a joke and draw an ascii art of the last word. please use the plugins"
3. Wait for the response

**Expected behavior**
Use both plugins and provide me ASCII art of the last word of the joke.

**Environment Information (please complete the following information):**
 - OS: Windows
 - Python Version 3.10
 - LLM that you're using: Azure Openai gpt-35-turbo

**Comment by liqul** [comment]
The generated code is wrong. There is no such module named `plugins` which is haullucinated by the LLM. This is typically not a persistent error.
