### ISSUE TITLE
Planner failed to generate response because Post send_to field is None

### ISSUE THREAD

**Issue by Chronoz** [microsoft/TaskWeaver#25]
**Describe the bug**
Planner failed to generate response because Post send_to field is None

**To Reproduce**
I use local llm from lmstudio server

**Expected behavior**
A clear and concise description of what you expected to happen. NA if feel not applicable.
with config_file as:
{
"llm.api_base": "http://localhost:1234/v1",
"llm.api_key": "sk-123",
"llm.model": "openhermes-2.5-mistral-7b.Q4_K_S.gguf"
}
{
"llm.api_base": "http://localhost:1234/v1",
"llm.api_key": "sk-123",
"llm.model": "openhermes-2.5-mistral-7b.Q4_K_S.gguf"
}
THE PROMPT
Human: print out 5 prime numbers

AFTER 5 mins
Error: Cannot process your request due to Exception: Planner failed to generate response because Post send_to field is None 
 Traceback (most recent call last):
  File "/Users/tringuyen/TaskWeaver/taskweaver/planner/planner.py", line 198, in reply
    response_post = self.planner_post_translator.raw_text_to_post(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tringuyen/TaskWeaver/taskweaver/role/translator.py", line 65, in raw_text_to_post
    validation_func(post)
  File "/Users/tringuyen/TaskWeaver/taskweaver/planner/planner.py", line 190, in check_post_validity
    assert post.send_to is not None, "Post send_to field is None"
           ^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Post send_to field is None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tringuyen/TaskWeaver/taskweaver/session/session.py", line 125, in send_message
    post = _send_message(post.send_to, post)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tringuyen/TaskWeaver/taskweaver/session/session.py", line 97, in _send_message
    reply_post = self.planner.reply(
                 ^^^^^^^^^^^^^^^^^^^
  File "/Users/tringuyen/TaskWeaver/taskweaver/planner/planner.py", line 219, in reply
    raise Exception(f"Planner failed to generate response because {str(e)}")
Exception: Planner failed to generate response because Post send_to field is None

**Screenshots**

**Environment Information (please complete the following information):**
 - OS: Mac M1 Sonoma
 - Python Version 3.11.5
 - LLM that you're using: OpenHermes2.5

**Comment by zhangxu0307** [comment]
The issue might be due to an incorrect response from LLM, as we verify all required fields in the generated JSON text. If any missing fields are found, an exception arises.

**Comment by j-loquat** [comment]
You must set llm.response_format parameter in json config file of taskweaver to "text". 
The api on local llm cannot talk in the default json setting.

**Comment by j-loquat** [comment]
I get a similar error running local model - but not every time:
Error: Cannot process your request due to Exception: 'NoneType' object has no attribute 'content'
 Traceback (most recent call last):
  File "C:\PythonPlay\TaskWeaver\taskweaver\session\session.py", line 125, in send_message
    post = _send_message(post.send_to, post)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonPlay\TaskWeaver\taskweaver\session\session.py", line 107, in _send_message
    reply_post = self.code_interpreter.reply(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonPlay\TaskWeaver\taskweaver\code_interpreter\code_interpreter.py", line 70, in reply
    code.content,
    ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'content'

**Comment by j-loquat** [comment]
Taskweaver does not "see" the sample_data folder - I had the same problem. Once you start a new taskweaver session, you have to find the latest session directory and go into the "cwd" directory of it (cwd stands for current working directory). If you put your file in there, you can then refer to it by name without a path and it will see it. I still have the errors above but it does find and work with my file.

**Comment by j-loquat** [comment]
Yes, I find if I keep the tasks simple or give it one step at a time, I can sometimes get things to complete without the error. I wonder what triggers that problem.
