### ISSUE TITLE
Azure Openai api issue

### ISSUE THREAD

**Issue by shivakharbanda** [microsoft/TaskWeaver#251]
**Describe the bug**
Not able to set deployment name and api version in my azure open ai config as its required for the api to be used in my case

**Expected behavior**
There is no information or provision given to add the deployment name and api version in the config

**Comment by liqul** [comment]
This is the page https://microsoft.github.io/TaskWeaver/docs/llms/aoai on using Azure OpenAI endpoint.

**Comment by liqul** [comment]
`llm.model` is the deployment name

**Comment by liqul** [comment]
close inactive issues
