### ISSUE TITLE
TaskWeaver cannot call its own plugin after using local olama

### ISSUE THREAD

**Issue by 13516513760** [microsoft/TaskWeaver#255]
I started llama2:13b locally through Ollama and then started Taskweaver, attempting to make taskweaver call plugins in/project/plugins, but Taskweaver was unable to call any of its own plugins.
If I change the configuration file of Taskweaver to gpt3.5, I can call all of its own plugins. Why? What should I do to make him start the local model and call his own plugins?

**Comment by liqul** [comment]
llama2:13b is typically not capable to generate output in the correct format or follow the instructions.

**Comment by 13516513760** [comment]
Thank you for your help!

**Comment by 13516513760** [comment]
> llama2:13b is typically not capable to generate output in the correct format or follow the instructions.

Can I use the plugin to make llama2:13b pass through Taskweaver through fine-tuning?

**Comment by liqul** [comment]
I'm not sure. The most challenging part is to follow the instructions in generating the right output format. This is a typical drawback of small models.

**Comment by liqul** [comment]
close inactive issues
