### ISSUE TITLE
The issue at hand is that the system begins to judge the content as incomplete without waiting for the LLM to return the results.

### ISSUE THREAD

**Issue by dxjjhm** [microsoft/TaskWeaver#258]
**Describe the bug**
add third party llm, 
it is a web socket service,
run llm_api_test ok
but, when do
  chainlit run app.py  or command line, 

Failed to parse LLM output due to LLM failed to generate complete attachments
Planner talk to Planner: failed to parse LLM output due to LLM failed to generate complete attachments

The issue at hand is that the system begins to judge the content as incomplete without waiting for the LLM to return the results.

**Comment by zhangxu0307** [comment]
Hi, @dxjjhm! Could you provide the model you used and the LLM output failed to be parsed by Planner?

**Comment by liqul** [comment]
close inactive issues
