### ISSUE TITLE
Inference time is too long

### ISSUE THREAD

**Issue by bala1802** [microsoft/TaskWeaver#269]
I am currently using the Sessions - [taskweaver_as_a_lib](https://microsoft.github.io/TaskWeaver/docs/usage/library/) to execute my request. 

![image](https://github.com/microsoft/TaskWeaver/assets/22103095/6c93c848-dcd2-44af-a110-903bfb6b7466)

The inference time is almost **~2 minutes for a simple query** like `What is the Revenue of XYZ?". The task is to extract the data from the uploaded excel sheets. 

**My Config**:

`{`
 ` "llm.api_base": "<API BASE>",`
  `"llm.api_key": "<API KEY>",`
  `"llm.api_type":"<API TYPE>",`
  `"llm.auth_mode":"api-key",`
  `"llm.model": "<MODEL>",`
  `"session.roles": ["planner", "code_interpreter"]`
`}`

I am aware that configuring `session.roles: ["code_interpreter"]` (Only Code Interpreter) will reduce the processing time, but my use case is demanding me to configure both the `Planner` and `Code Interpreter`.

**Device Specification**

![image](https://github.com/microsoft/TaskWeaver/assets/22103095/ccc9f5a4-4c43-4009-b3f0-49ba9c1b9296)

Any suggestions or best practices to follow ?

Thanks in advance

**Comment by liqul** [comment]
One idea is to configure different models for different roles. Please refer to https://microsoft.github.io/TaskWeaver/docs/llms/multi-llm. So, you can configure a quicker model for the planner.

**Comment by liqul** [comment]
close inactive issues
