### ISSUE TITLE
Gemini API error

### ISSUE THREAD

**Issue by sangeet000007** [microsoft/TaskWeaver#270]
i am using gemini pro api and taskweaver in google colab i get the following error 

 File "/content/TaskWeaver/taskweaver/ces/environment.py", line 145, in __init__
    raise docker.errors.DockerException(f"Failed to connect to Docker daemon: {e}. ")
docker.errors.DockerException: Failed to connect to Docker daemon: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory')). 

i put api json file in correct directory and i have checked api with curl its working

**Comment by liqul** [comment]
We have switched to running code inside docker container by default. It seems that you haven't install docker on your machine. So, please either install docker or switch to the `local` mode. Check this document https://microsoft.github.io/TaskWeaver/docs/advanced/code_execution

**Comment by sangeet000007** [comment]
i am using google colab and i have not installed docker  and i cant find how to switch to local mode so kindly provide the instruction to set local mode

**Comment by liqul** [comment]
set "execution_service.kernel_mode"="local" in your config file

**Comment by sangeet000007** [comment]
set in project/taskweaver_config.json
issue resolved

**Comment by sangeet000007** [comment]
.
