### ISSUE TITLE
Help Needed: Integrating Taskweaver with Litellm on Cloudflare Workers

### ISSUE THREAD

**Issue by bpawnzZ** [microsoft/TaskWeaver#274]
Description:

I'm currently facing an issue while attempting to integrate Taskweaver with Litellm using Cloudflare Workers. Despite following the setup instructions, I'm encountering an error that I'm unable to resolve. Below is a detailed explanation of the problem along with the relevant code snippets:

Error Message:

```
Error: Cannot process your request due to Exception: Planner failed to generate response because Missing elements: send_to, message, init_plan, plan, current_plan_step in the `response` element 
 Traceback (most recent call last):
  File "/home/amnesia/git/TaskWeaver/taskweaver/planner/planner.py", line 309, in reply
    self.planner_post_translator.raw_text_to_post(
  File "/home/amnesia/git/TaskWeaver/taskweaver/role/translator.py", line 139, in raw_text_to_post
    validation_func(post_proxy.post)
  File "/home/amnesia/git/TaskWeaver/taskweaver/planner/planner.py", line 271, in check_post_validity
    assert len(validation_errors) == 0, ";".join(validation_errors)
AssertionError: Missing elements: send_to, message, init_plan, plan, current_plan_step in the `response` element

```

Explanation:
The error message indicates that there are missing elements in the response generated by the Taskweaver planner. Specifically, it's expecting elements like send_to, message, init_plan, plan, and current_plan_step, but they are not present in the response.

Code Snippets:

LiteLLM Proxy Config:

```
model_list: 
  - model_name: "@hf/thebloke/openchat_3.5-awq"
    litellm_params: 
      model: "cloudflare/@hf/thebloke/openchat_3.5-awq"
      messages: 
        role: "manager"  # Updated role to manager
        content: "hello from litellm"
      # max_tokens: 150  # Example value, adjust as needed
      stream: true
      prompt_tokens: 12
      completion_tokens: 26
      total_tokens: 38
      finish_reason: stop
      index: 0
      # temperature: 0.6  # Example value, adjust as needed
      # top_p: 0.8  # Example value, adjust as needed
      # presence_penalty: 0.3  # Example value, adjust as needed
      # frequency_penalty: 0.4  # Example value, adjust as needed
      # stop: "\n"  # Example value, adjust as needed
      timeout: 5  # Example value, adjust as needed
      # n: 1  # Example value, adjust as needed # Add this line
    api_base: http://127.0.0.1:4000
cloudflare_api_key: ""
cloudflare_account_id: ""
```

Taskweaver Config:

```
{
  "llm.api_base": "http://127.0.0.1:4000",
  "llm.api_key": "anything",
  "llm.model": "@hf/thebloke/openchat_3.5-awq"
}

```

I've reviewed both the Taskweaver and Litellm configurations, but I'm unable to pinpoint the exact cause of the issue. Could someone please look over the provided code snippets and offer advice on how to resolve this error? Any insights or suggestions would be greatly appreciated.  It appears as thought I am speaking to the proxy correctly. Any help would be appreciated.

Thank you in advance for your assistance!

**Comment by liqul** [comment]
Please refer to our FAQ. This usually means that the model is not capable enough to generate the right output format.

**Comment by liqul** [comment]
close inactive issues
