### ISSUE TITLE
Running into an error "Complex assignments are not allowed"

### ISSUE THREAD

**Issue by sy276** [microsoft/TaskWeaver#277]
**Describe the bug**
Running into the following error when trying to call **sql_pull_data** plugin - 
`Error on line 1: df_employees, description_employees = sql_pull_data("pull data from employees table") => Complex assignments are not allowed`

**To Reproduce**
1. Set the code verification to true in the config file like this `"code_interpreter.code_verification_on": true`
2. Have some data ready in the db file
3. Ask TaskWeaver to pull the data from the database

**Expected behavior**
I expect TaskWeaver to pull the data from the db along with the description of what it pulled.

**Environment Information:**
 - OS: Linux
 - Python Version: 3.10.13
 - LLM that you're using: Google Gemini
 - Other Configurations: `"code_interpreter.code_verification_on": true`

**Comment by sy276** [comment]
@liqul - I am still facing the issue with the `sql_pull_data` plugin when `code_interpreter.code_verification_on` is set to `true`. Since the issue was closed without providing a resolution, I wanted to bring this to your attention again.

As a workaround, I’m considering simplifying the assignment as follows:
`df_employees = sql_pull_data("pull data from employees table")`

However, this modification doesn’t return the description of the data pulled, which is part of the expected behavior.

Would you recommend simplifying the assignment like this? Or is there another way we can resolve this issue while still pulling the description of the data?

Thank you for your time and consideration.

**Comment by liqul** [comment]
> @liqul - I am still facing the issue with the `sql_pull_data` plugin when `code_interpreter.code_verification_on` is set to `true`. Since the issue was closed without providing a resolution, I wanted to bring this to your attention again.
> 
> As a workaround, I’m considering simplifying the assignment as follows: `df_employees = sql_pull_data("pull data from employees table")`
> 
> However, this modification doesn’t return the description of the data pulled, which is part of the expected behavior.
> 
> Would you recommend simplifying the assignment like this? Or is there another way we can resolve this issue while still pulling the description of the data?
> 
> Thank you for your time and consideration.

May I know more on why you need to turn on the code verification on since this is blocked by a pre-defined verification rule.

**Comment by sy276** [comment]
> > @liqul - I am still facing the issue with the `sql_pull_data` plugin when `code_interpreter.code_verification_on` is set to `true`. Since the issue was closed without providing a resolution, I wanted to bring this to your attention again.
> > As a workaround, I’m considering simplifying the assignment as follows: `df_employees = sql_pull_data("pull data from employees table")`
> > However, this modification doesn’t return the description of the data pulled, which is part of the expected behavior.
> > Would you recommend simplifying the assignment like this? Or is there another way we can resolve this issue while still pulling the description of the data?
> > Thank you for your time and consideration.
> 
> May I know more on why you need to turn on the code verification on since this is blocked by a pre-defined verification rule.

I enabled code verification to restrict TaskWeaver's package installation and import capabilities. This ensures TaskWeaver only accesses whitelisted modules in allowed_modules config setting. This also helps prevent unauthorized system file access and files from other sessions. I think this added security is particularly important for local runs outside of Docker.

**Comment by liqul** [comment]
Please pull the latest version and try again.

**Comment by sy276** [comment]
> Please pull the latest version and try again.

I pulled the latest version and it's working without issues now. Thanks @liqul! 

Closing the issue now.
