### ISSUE TITLE
qwen api 500 error

### ISSUE THREAD

**Issue by yyghefei** [microsoft/TaskWeaver#279]
**Describe the bug**
when use qwen model and  the taskweaver run in the web ui, The program will fail and report a 500 error And prompt unreasonable parameters.
What is the reason for this? Other models such as OpenAI will not have similar errors.

**Comment by liqul** [comment]
Is your issue the same with this one https://github.com/microsoft/TaskWeaver/issues/280

**Comment by liqul** [comment]
close inactive issues
