### ISSUE TITLE
Permissions assignment failed for secure file: Got '0o677' instead of '0o0600'.

### ISSUE THREAD

**Issue by georgehu0815** [microsoft/TaskWeaver#287]
**Describe the bug**
When run in execution_service in local model, it reached the issue.

{
  "llm.api_base": "https://<env>.openai.azure.com/",
  "llm.api_key": "<key>",
  "llm.api_type":"azure",
  "llm.api_version":"2024-02-15-preview",
  "llm.model": "gpt-4",
  "llm.response_format":null,
  "execution_service.kernel_mode":"local"
}

**To Reproduce**
1. Start the service and go to UI
2. Type the user query "genarate 100 random numbers"
3. Wait for the response
4. Type the user query "yyy"
5.     kw = await self.provisioner.pre_launch(**kw)
  File "/home/bochuxt/.local/lib/python3.10/site-packages/jupyter_client/provisioning/local_provisioner.py", line 190, in pre_launch
    km.write_connection_file()
  File "/home/bochuxt/.local/lib/python3.10/site-packages/jupyter_client/connect.py", line 503, in write_connection_file
    self.connection_file, cfg = write_connection_file(
  File "/home/bochuxt/.local/lib/python3.10/site-packages/jupyter_client/connect.py", line 164, in write_connection_file
    with secure_write(fname) as f:
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/home/bochuxt/.local/lib/python3.10/site-packages/jupyter_core/paths.py", line 999, in secure_write
    raise RuntimeError(msg)
RuntimeError: Permissions assignment failed for secure file: '/mnt/a/TaskWeaver2/project/workspace/sessions/20240407-163322-113f9167/ces/conn-20240407-163322-113f9167-knl-61c09b99b25f.json'. Got '0o677' instead of '0o0600'.
<img width="745" alt="image" src="https://github.com/microsoft/TaskWeaver/assets/116222457/ac9e38cb-0b62-4d05-b1f0-919fad186d9a">

**Expected behavior**

A clear and concise description of what you expected to happen. NA if feel not applicable.

**Screenshots**

**Environment Information (please complete the following information):**
 - OS: [ WSL]
 - Python Version [e.g. 3.10, 3.11]
 - LLM that you're using: [GPT-4]
 - Other Configurations except the LLM api/key related: [e.g., code_verification: true]

**Additional context**

**Comment by liqul** [comment]
Thanks for reporting this issue. I found an issue [here](https://github.com/jupyter/notebook/issues/5428) saying this is caused by the WSL file system permission. A workaround would be setting the environment variable JUPYTER_ALLOW_INSECURE_WRITES=true as described there.

**Comment by georgehu0815** [comment]
works now, thanks for your help. you can close this ticket.
