### ISSUE TITLE
TaskWeaver UI frontend

### ISSUE THREAD

**Issue by amitlals** [microsoft/TaskWeaver#30]
**Is your feature request related to a problem? Please describe.**
Please provide insight how we can leverage chainlit or other UI enabled on TaskWeaver for demos

**Comment by liqul** [comment]
We are working on a frontend

**Comment by ShilinHe** [comment]
Hi @amitlals we have developed a simple UI using chainlit for demonstration purpose. Please go to playground/UI for more information.
