### ISSUE TITLE
Planner Missing elements

### ISSUE THREAD

**Issue by AstronautChi** [microsoft/TaskWeaver#302]
**Describe the bug**
I entered the local mode of Taskweaver via the command line. And then input some simple tasks.
 After that, the following error message appeared.

**To Reproduce**
1. Start the service
2. Type the user query "xxx"
3. Wait for the response

**Screenshots**
![image](https://github.com/microsoft/TaskWeaver/assets/79776131/ee143e18-7218-4dd6-8efe-26ca7b9515fd)

**Environment Information (please complete the following information):**
 - OS: Fedora release 39
 - Python Version 3.12
 - LLM that you're using: My own LLM

**Comment by ShilinHe** [comment]
Please refer to the [FAQs](https://microsoft.github.io/TaskWeaver/docs/FAQ#q-why-i-see-errors-saying-the-planner-failed-to-generate-the-send_to-message-or-other-fields) here. In short, the model has limited capability and cannot follow instructions well.

**Comment by glufy100** [comment]
> Please refer to the [FAQs](https://microsoft.github.io/TaskWeaver/docs/FAQ#q-why-i-see-errors-saying-the-planner-failed-to-generate-the-send_to-message-or-other-fields) here. In short, the model has limited capability and cannot follow instructions well.

I have the same bug it come from taskweaver i use codelama 70B and i have it

**Comment by GihanMora** [comment]
Have the same bug with gpt-3.5-16k
