### ISSUE TITLE
test failed ，PermissionError

### ISSUE THREAD

**Issue by Younthing** [microsoft/TaskWeaver#309]
linux ubuntu 22.04；rootless docker

PermissionError: [Errno 13] Permission denied: '/work/run/projects/fanxi/learn/TaskWeaver/project/workspace/sessions/20240417-023455-0ebb82b7/ces/ports.json'

![tmpA889](https://github.com/microsoft/TaskWeaver/assets/70081072/853acb78-afe7-4130-831f-d78407e85e83)

**Comment by shivakharbanda** [comment]
sudo chmod -R 777 .

try this command in the root directory

**Comment by Younthing** [comment]
> sudo chmod -R 777 .
> 
> try this command in the root directory

thanks a lot, but im in rootless，just only run local but container
