### ISSUE TITLE
Discord channel for TaskWeaver?

### ISSUE THREAD

**Issue by amitlals** [microsoft/TaskWeaver#31]
Do you have any discord server for TaskWeaver? pls share details

**Comment by willgodfrey** [comment]
agreed!

**Comment by orkutmuratyilmaz** [comment]
+1

**Comment by marcindulak** [comment]
I hope the arguments for and against it will be considered https://blog.mattcen.com/2023/07/04/stop-using-discord-for-your-open-source-communities/

**Comment by amitlals** [comment]
> I hope the arguments for and against it will be considered https://blog.mattcen.com/2023/07/04/stop-using-discord-for-your-open-source-communities/

Agree!! We host our Semantic Kernel and Autogen frameworks on Discord without any issues. Enabling Discord should foster active community participation, in my opinion.

**Comment by marcindulak** [comment]
> > I hope the arguments for and against it will be considered https://blog.mattcen.com/2023/07/04/stop-using-discord-for-your-open-source-communities/
> 
> Agree!! We host our Semantic Kernel and Autogen frameworks on Discord without any issues. Enabling Discord should foster active community participation, in my opinion.

Citing from the above link, the arguments against discord or other service outside of github issues

> The short version of why I don’t like Discord for this use-case is:
> - I need to join Yet Another Server to be able to see chat history for a given community
> - I need an account to join that server
> - I need to use the Discord website or app, which often has flashy distractions and “What’s new” pop-ups[1](https://blog.mattcen.com/2023/07/04/stop-using-discord-for-your-open-source-communities/#fn:1)
> - Searching history to see if my question has already been answered is hard
> - If a community decides to move from Discord to another platform down the line, it is likely tricky (if not impossible) to export all that discussion content elsewhere, given Discord is a walled garden

**Comment by ShilinHe** [comment]
Thank you all for the great suggestions! Discord is now available, please check the latest README News or the [TaskWeaver website](https://microsoft.github.io/TaskWeaver/) for more information.
