### ISSUE TITLE
Taskweaver with multiple LLMs seems not working

### ISSUE THREAD

**Issue by GihanMora** [microsoft/TaskWeaver#314]
**Describe the bug**
I am trying to implement Taskweaver with multiple LLM settings. But apparently it is not picking up specified LLMs for code generator and planner. It just uses the default llm specified on the top.

**To Reproduce**
1. Add the following to taskweaver_config.json.
```
{
  "llm.api_base": "",
  "llm.api_key": "",
  "llm.api_type": "azure",
  "llm.api_version": "2023-07-01-preview",
  "llm.model": "gpt-35-turbo-1106-16k-ptu",
  "llm.response_format": "text",
  "llm.embedding_api_type": "openai",
  "llm.embedding_model": "text-embedding-ada-002",
  "execution_service.kernel_mode" : "local",
  "ext_llms.llm_configs": {
    "llm_A":
        {
              "llm.api_base": "",
              "llm.api_key": "",
              "llm.api_type": "azure",
              "llm.api_version": "2023-07-01-preview",
              "llm.model": "gpt-4-32k-0613-32k-payg",
              "llm.response_format": "text",
              "llm.embedding_api_type": "openai",
              "llm.embedding_model": "text-embedding-ada-002",
              "execution_service.kernel_mode" : "local"
        },
    "llm_B":
        {
              "llm.api_base": "",
              "llm.api_key": "",
              "llm.api_type": "azure",
              "llm.api_version": "2023-07-01-preview",
              "llm.model": "gpt-35-turbo-1106-16k-ptu",
              "llm.response_format": "text",
              "llm.embedding_api_type": "openai",
              "llm.embedding_model": "text-embedding-ada-002",
              "execution_service.kernel_mode" : "local"
        }
},
  "planner.llm_alias": "llm_A",
  "code_generator.llm_alias": "llm_B"
}
```
3. Run the taskweaver

**Expected behavior**
Planner should use GPT4 and code_interpretor should use GPT3.5. I have hidden the keys and base in the above configuration settings. Any guidance is highly appreciated.
Thanks in Advance.

**Comment by liqul** [comment]
Thanks for reporting this issue. There is currently a bug where the planner fails to consume this configuration. Will fix it soon.

**Comment by GihanMora** [comment]
If somebody is looking for a remedy until then.
How it works is, the model you set with default llm settings(on top) will be used by the planner. Code interpreter llm will be used from the multi-llm params. So give the required llms on those places. llms specified with multi-llm params for the planner will be simply ignored.

So your planner llm = default llm
code interpreter llm = llm you give in multi-llm params

**Comment by GihanMora** [comment]
If somebody is looking for a remedy until then.
How it works is, the model you set with default llm settings(on top) will be used by the planner. Code interpreter llm will be used from the multi-llm params. So give the required llms on those places. llms specified with multi-llm params for the planner will be simply ignored.

So your planner llm = default llm
code interpreter llm = llm you give in multi-llm params

**Comment by GihanMora** [comment]
If someone is looking for a solution, until it gets fixed,
Currently how it works is the Code_interpreter will use the multi_llm params. And planner will ignore the the multi_llm params. So whatever you put as default llm will be used by the planner. 

So set you preferred llms in the following places.
llm for planner = set in default params
llm for code_interpreter = set in the multi_llm params
