### ISSUE TITLE
plugin doesn't work well when I save artifact

### ISSUE THREAD

**Issue by ksd1221** [microsoft/TaskWeaver#315]
**Describe the bug**
I have customized a data preprocessing plugin, and the execution code includes the 'add_artifact' function to save the preprocessed files. However, I keep encountering errors because the files are automatically being saved in the '/app/cwd/cwd' directory, which does not exist. I believe the correct path should be '/app/cwd', as files stored there do not cause any errors. Since I did not specify a storage location in the plugin function, it seems there is a bug in the code you provided that causes this issue. Please fix this.

Additionally, according to your paper and documentation, the Code Interpreter (CI) uses plugins and examples to generate code when interacting with the LLM. However, in practice, I've noticed that the CI sometimes arbitrarily modifies the contents of my custom plugins, leading to errors. It seems more appropriate for the Agent to have some understanding of the dataset and provide suggestions to the CI, which would then consider these suggestions during code generation. Currently, this kind of interaction is not happening. I'm wondering if this is because the implementation is still in progress or if there is no intention to implement such a feature in the future.

**Screenshots**
preprocess each dataset using 'preprocess_used_car_data' plugin. you should use dataset and file name as parameters when you call plugin.
 ╭───< Planner >
 ├─► [init_plan]
 │   1. Preprocess 'used_car_test.csv' using 'preprocess_used_car_data' plugin
 │   2. Preprocess 'used_car_train.csv' using 'preprocess_used_car_data' plugin
 ├─► [plan] 1. Preprocess 'used_car_test.csv' and 'used_car_train.csv' using 'preprocess_used_car_data' plugin
 ├─► [current_plan_step] 1. Preprocess 'used_car_test.csv' and 'used_car_train.csv' using 'preprocess_used_car_data' plugin
 ├──● Please preprocess 'used_car_test.csv' using 'preprocess_used_car_data' plugin with the dataset name as 'used_car_test'. Then, preprocess 'used_car_train.csv' using the same plugin with the dataset name as 
 │   'used_car_train'.
 ├─► [board]
 │   I have drawn up a plan: 
 │   1. Preprocess 'used_car_test.csv' and 'used_car_train.csv' using 'preprocess_used_car_data' plugin
 │   
 │   Please proceed with this step of this plan: Please preprocess 'used_car_test.csv' using 'preprocess_used_car_data' plugin with the dataset name as 'used_car_test'. Then, preprocess 'used_car_train.csv' using the 
 │   same plugin with the dataset name as 'used_car_train'.
 ╰──● sending message to CodeInterpreter
 ╭───< CodeInterpreter >
 ├─► [thought] To fulfill the user's request, ProgramApe will call the 'preprocess_used_car_data' plugin for both 'used_car_test' and 'used_car_train' datasets. Since direct plugin importation and execution are required 
 │   without explicitly importing the plugin, the code will be structured to reflect a call to these plugins as if they were being directly invoked, adhering to the instructions provided.
 ├─► [python]
 │   # Preprocessing 'used_car_test.csv' and 'used_car_train.csv' using 'preprocess_used_car_data' plugin
 │   preprocessed_test, description_test = preprocess_used_car_data(used_car_test)
 │   preprocessed_train, description_train = preprocess_used_car_data(used_car_train)
 │   
 │   # Placing the result variables in the last line as per instructions
 │   preprocessed_test, description_test, preprocessed_train, description_train
 ├─► [verification] NONE
 ├─► [code_error] No code verification is performed.
 ├─► [execution_status] FAILURE
 ├─► [execution_result]
 │   The execution of the generated python code above has failed
 │   
 │   During execution, the following messages were logged:
 │   Traceback (most recent call last):
 │   
 │     Cell In[10], line 2
 │       preprocessed_test, description_test = preprocess_used_car_data(used_car_test)
 │   
 │   TypeError: UsedCarPreprocessingPlugin.__call__() missing 1 required positional argument: 'file_name'
 │   
 │   
 ├─► [artifact_paths] []
 ├──● The following python code has been executed:
 │   ```python
 │   # Preprocessing 'used_car_test.csv' and 'used_car_train.csv' using 'preprocess_used_car_data' plugin
 │   preprocessed_test, description_test = preprocess_used_car_data(used_car_test)
 │   preprocessed_train, description_train = preprocess_used_car_data(used_car_train)
 │   
 │   # Placing the result variables in the last line as per instructions
 │   preprocessed_test, description_test, preprocessed_train, description_train
 │   ```
 │   
 │   
 │   The execution of the generated python code above has failed
 │   
 │   During execution, the following messages were logged:
 │   Traceback (most recent call last):
 │   
 │     Cell In[10], line 2
 │       preprocessed_test, description_test = preprocess_used_car_data(used_car_test)
 │   
 │   TypeError: UsedCarPreprocessingPlugin.__call__() missing 1 required positional argument: 'file_name'
 │   
 │   
 ├─► [revise_message]
 │   The execution of the previous generated code has failed. If you think you can fix the problem by rewriting the code, please generate code and run it again.
 │   Otherwise, please explain the problem to me.
 ╰──● sending message to CodeInterpreter
 ╭───< CodeInterpreter >
 ├─► [thought] The error message indicates that the 'preprocess_used_car_data' plugin call was missing a required 'file_name' argument. This oversight can be corrected by including the 'file_name' parameter in the plugin
 │    function calls for both datasets. Given the constraints and instructions, the code will be adjusted to correctly call the plugin with all necessary parameters, including the dataset and its corresponding file name,
 │    without attempting to import the plugin directly.
 ├─► [python]
 │   # Correcting the plugin call by including the 'file_name' parameter
 │   preprocessed_test, description_test = preprocess_used_car_data(used_car_test, 'used_car_test.csv')
 │   preprocessed_train, description_train = preprocess_used_car_data(used_car_train, 'used_car_train.csv')
 │   
 │   # Placing the result variables in the last line as per instructions
 │   preprocessed_test, description_test, preprocessed_train, description_train
 ├─► [verification] NONE
 ├─► [code_error] No code verification is performed.
 ├─► [execution_status] FAILURE
 ├─► [execution_result]
 │   The execution of the generated python code above has failed
 │   
 │   During execution, the following messages were logged:
 │   Traceback (most recent call last):
 │   
 │     Cell In[11], line 2
 │       preprocessed_test, description_test = preprocess_used_car_data(used_car_test, 'used_car_test.csv')
 │   
 │     File /tmp/tmp6jgc51q7/preprocess_used_car_data.py:47 in __call__
 │   
 │     File /app/taskweaver/ces/runtime/context.py:50 in add_artifact
 │       val.to_csv(path, index=False)
 │   
 │     File /usr/local/lib/python3.10/site-packages/pandas/util/_decorators.py:333 in wrapper
 │       return func(*args, **kwargs)
 │   
 │     File /usr/local/lib/python3.10/site-packages/pandas/core/generic.py:3967 in to_csv
 │       return DataFrameRenderer(formatter).to_csv(
 │   
 │     File /usr/local/lib/python3.10/site-packages/pandas/io/formats/format.py:1014 in to_csv
 │       csv_formatter.save()
 │   
 │     File /usr/local/lib/python3.10/site-packages/pandas/io/formats/csvs.py:251 in save
 │       with get_handle(
 │   
 │     File /usr/local/lib/python3.10/site-packages/pandas/io/common.py:749 in get_handle
 │       check_parent_directory(str(handle))
 │   
 │     File /usr/local/lib/python3.10/site-packages/pandas/io/common.py:616 in check_parent_directory
 │       raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
 │   
 │   OSError: Cannot save file into a non-existent directory: '/app/cwd/cwd'
 │   
 │   
 │   The following artifacts were generated:
 │   - type: df ; uri: file:///Users/a09164/Desktop/sodam/TaskWeaver/project/workspace/sessions/20240424-060917-ef379f16/cwd/obj_11_df_0000_preprocessed_used_car_data_test.csv ; description: DataFrame in shape (48812, 
 │   24) with columns ['maker', 'main_class', 'class', 'model', 'trim', 'model_year', 'type', 'main_color', 'color_grp', 'trans', 'fuel', 'drive_mode', 'displacement', 'car_age_Y', 'car_age_M', 'distance', 
 │   'rec_distance', 'in_distance', 'accident_grd', 'accident_yn', 'in_distance_yn', 'auto_yn', 'main_color_yn', 'new_price']
 │   
 ├─► [artifact_paths] ['/Users/a09164/Desktop/sodam/TaskWeaver/project/workspace/sessions/20240424-060917-ef379f16/cwd/obj_11_df_0000_preprocessed_used_car_data_test.csv']
 ├──● The following python code has been executed:
 │   ```python
 │   # Correcting the plugin call by including the 'file_name' parameter
 │   preprocessed_test, description_test = preprocess_used_car_data(used_car_test, 'used_car_test.csv')
 │   preprocessed_train, description_train = preprocess_used_car_data(used_car_train, 'used_car_train.csv')
 │   
 │   # Placing the result variables in the last line as per instructions
 │   preprocessed_test, description_test, preprocessed_train, description_train
 │   ```
 │   
 │   
 │   The execution of the generated python code above has failed
 │   
 │   During execution, the following messages were logged:
 │   Traceback (most recent call last):
 │   
 │     Cell In[11], line 2
 │       preprocessed_test, description_test = preprocess_used_car_data(used_car_test, 'used_car_test.csv')
 │   
 │     File /tmp/tmp6jgc51q7/preprocess_used_car_data.py:47 in __call__
 │   
 │     File /app/taskweaver/ces/runtime/context.py:50 in add_artifact
 │       val.to_csv(path, index=False)
 │   
 │     File /usr/local/lib/python3.10/site-packages/pandas/util/_decorators.py:333 in wrapper
 │       return func(*args, **kwargs)
 │   
 │     File /usr/local/lib/python3.10/site-packages/pandas/core/generic.py:3967 in to_csv
 │       return DataFrameRenderer(formatter).to_csv(
 │   
 │     File /usr/local/lib/python3.10/site-packages/pandas/io/formats/format.py:1014 in to_csv
 │       csv_formatter.save()
 │   
 │     File /usr/local/lib/python3.10/site-packages/pandas/io/formats/csvs.py:251 in save
 │       with get_handle(
 │   
 │     File /usr/local/lib/python3.10/site-packages/pandas/io/common.py:749 in get_handle
 │       check_parent_directory(str(handle))
 │   
 │     File /usr/local/lib/python3.10/site-packages/pandas/io/common.py:616 in check_parent_directory
 │       raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
 │   
 │   OSError: Cannot save file into a non-existent directory: '/app/cwd/cwd'
 │   
 │   
 │   The following artifacts were generated:
 │   - type: df ; uri: file:///Users/a09164/Desktop/sodam/TaskWeaver/project/workspace/sessions/20240424-060917-ef379f16/cwd/obj_11_df_0000_preprocessed_used_car_data_test.csv ; description: DataFrame in shape (48812, 
 │   24) with columns ['maker', 'main_class', 'class', 'model', 'trim', 'model_year', 'type', 'main_color', 'color_grp', 'trans', 'fuel', 'drive_mode', 'displacement', 'car_age_Y', 'car_age_M', 'distance', 
 │   'rec_distance', 'in_distance', 'accident_grd', 'accident_yn', 'in_distance_yn', 'auto_yn', 'main_color_yn', 'new_price']
 │   
 ├─► [revise_message]
 │   The execution of the previous generated code has failed. If you think you can fix the problem by rewriting the code, please generate code and run it again.
 │   Otherwise, please explain the problem to me.
 ╰──● sending message to CodeInterpreter
 ╭───< CodeInterpreter >
 ├─► [thought] The error encountered during execution is related to an attempt to save a file into a non-existent directory, which is an issue with the plugin's internal operation rather than the code provided to call 
 │   the plugin. Given the constraints and instructions, and considering the plugin's operation is beyond ProgramApe's control, the appropriate response is to acknowledge the execution issue and clarify the limitations.
 ├─► [text] The error encountered is due to an internal operation of the 'preprocess_used_car_data' plugin, specifically an attempt to save a file into a non-existent directory. This issue is beyond the scope of 
 │   adjustments I can make in the code provided for calling the plugin. The plugin's functionality, including file operations, is managed internally and cannot be corrected through changes to the code used to invoke the
 │    plugin. Please ensure the plugin's environment is correctly configured to access the specified directories.
 ├──● The error encountered is due to an internal operation of the 'preprocess_used_car_data' plugin, specifically an attempt to save a file into a non-existent directory. This issue is beyond the scope of adjustments I 
 │   can make in the code provided for calling the plugin. The plugin's functionality, including file operations, is managed internally and cannot be corrected through changes to the code used to invoke the plugin. 
 │   Please ensure the plugin's environment is correctly configured to access the specified directories.

**Environment Information (please complete the following information):**
 - OS: Mac
 - Python Version: 3.11
 - LLM that you're using: GPT-4
 - Other Configurations except the LLM api/key related: nothing

**Comment by liqul** [comment]
Thanks for reporting this issue. There is a bug on composing the artifact path. Will fix soon.
