### ISSUE TITLE
Request for Scatter plot default marker modify

### ISSUE THREAD

**Issue by wmjoo** [microsoft/TaskWeaver#326]
Hi, I'm writing to ask for suggestions while modifying the config.py file to resolve an issue (#323) I left a few days ago.
(./TaskWeaver/taskweaver/ces/kernel/config.py)

In general, when drawing a scatter plot, user wants the marker to be an 'o' shape, but in Taskweaver's configuration, the default setting is an 'x' shape.

![image](https://github.com/microsoft/TaskWeaver/assets/38180565/236e2860-cfe8-4b74-acdf-7d869e169273)

For reference. one of The most popular python visualization library 'matplotlib', the default setting for scatter plot's marker shape is 'o'.
![image](https://github.com/microsoft/TaskWeaver/assets/38180565/b9178a72-5b31-440d-bf55-ebf6cd9c0423)

So, I would like to ask you to change the default to 'o' in this area.
Thank you.

**Comment by liqul** [comment]
I would consider this as a personal preference :)

**Comment by liqul** [comment]
close inactive issues
