### ISSUE TITLE
Does Taskweaver works with llama3?

### ISSUE THREAD

**Issue by SingTeng** [microsoft/TaskWeaver#336]
**Describe the bug**

I tried to use llama3 via ollama.
After setting up the configuration file, I tried to do:
cd scripts
python llm_api_test.py

It produces a {}, and then went crazy after that with no output, I have to force cancel it.
I tried again by switching stream to false, it still produce no output when testing with llm_api_test.

My question is, has anyone tested Taskweaver on llama3 via ollama before? Is it suppose to work?

I tried to start Taskweaver on llama3, it run a bit then stuck, hence I thought I should run llm_api_test.py and it tells me the llama3 is not working on Taskweaver. 
Llama2 works ok. 

**To Reproduce**

1. install Ollama
2. Use llama3 model via Ollama in Taskweaver

**Expected behavior**

**Screenshots**

**Environment Information (please complete the following information):**

**Additional context**

**Comment by liqul** [comment]
We haven't tested on llama3 with ollama. But your test looks a bit strange as the script only sends a 'Hello' to the LLM endpoint. Could you share more details of your configuration file? From the '{}' output, you may change this setting "llm.ollama.response_format" to "text", just for testing.

**Comment by SingTeng** [comment]
You are a legend. After I add llm.response_format": "text" to config file, then it works.
Thank you !
