### ISSUE TITLE
No memory using only code_interperter (without planner)

### ISSUE THREAD

**Issue by gerglitzen** [microsoft/TaskWeaver#344]
I'm using
```
  "execution_service.kernel_mode": "local",
  "session.roles": ["code_interpreter"]
```
I face into the problem, that in this way, the app do not has memory. I looked back the log files, and I found that the prompts are extended with my questions, but with the app's answer no.
![image](https://github.com/microsoft/TaskWeaver/assets/38277364/16abc451-c00e-46dd-8873-3bb96ae5347c)
(There are just _user_ messages but _assistant_ answer is missing

For example, I ask which day is today, and than ask back. I tried both from UI both from code using as a library:
![UI](https://github.com/microsoft/TaskWeaver/assets/38277364/f299247b-80aa-48d5-b98d-8d85555e0c14)

Am I missing something from the config file, or how can I solve this?

**Comment by liqul** [comment]
You are right and I think this is caused by a bug. Will fix it.
