### ISSUE TITLE
he generated code `!pip install openpyxl` keeps failing when executed

### ISSUE THREAD

**Issue by HuggingTech** [microsoft/TaskWeaver#359]
**【BUG】

**The generated code `!pip install openpyxl` keeps failing when executed.  Translate the above into English:  The generated command `!pip install openpyxl` continues to fail upon execution.****

--------------------
The execution of the generated python code above has failed

During execution, the following messages were logged:
Traceback (most recent call last):

  Cell In[19], line 3
    from openpyxl import Workbook, load_workbook

ModuleNotFoundError: No module named 'openpyxl'

Defaulting to user installation because normal site-packages is not writeable
--------------------

Requirement already satisfied: openpyxl in /home/taskweaver/.local/lib/python3.10/site-packages (3.1.3)

Requirement already satisfied: et-xmlfile in /home/taskweaver/.local/lib/python3.10/site-packages (from openpyxl) (1.1.0)

![image](https://github.com/microsoft/TaskWeaver/assets/132802051/f0144d31-05c5-4070-ad00-714665535c96)

**Comment by liqul** [comment]
In general, if you can predict what dependency libraries would be needed during code execution, please install it manually. 

In this specific case, I don't know why the installation attempts failed, and I guess there should be some error messages on that.
