### ISSUE TITLE
Taskweaver can't run a plugin that uses pyodbc

### ISSUE THREAD

**Issue by pfekrati** [microsoft/TaskWeaver#361]
**Describe the bug**
I've created a plugin that uses pyodbc to get data from a SQL database. When Taskweaver tries to use the plugin it always returns an error message saying ModuleNotFoundError: No module named 'pyodbc'

**To Reproduce**
1. create a plugin that uses pydobd and register it
2. prompt anything that triggers the usage of that plugin

**Expected behavior**
I'm sure the code works fine because I tested it outside of Taskweaver plugin and I'm sure the pyodbc is installed

**Screenshots**
![image](https://github.com/microsoft/TaskWeaver/assets/106823811/ee63cb22-62c4-4d0b-a92c-517f26fdb081)

![image](https://github.com/microsoft/TaskWeaver/assets/106823811/acad3c20-ccfd-46d9-bab3-11fc11054828)

**Environment Information (please complete the following information):**
 - OS: Windows 11
 - Python Version: tested with both 3.9 and 3.11
 - LLM that you're using: GPT4o

**Additional context**
The execution of the generated python code above has failed

During execution, the following messages were logged:
Traceback (most recent call last):

  Cell In[5], line 2
    import pyodbc

ModuleNotFoundError: No module named 'pyodbc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  Cell In[5], line 5
    import pyodbc

ModuleNotFoundError: No module named 'pyodbc'

Requirement already satisfied: pyodbc in /home/taskweaver/.local/lib/python3.10/site-packages (5.1.0)

**Comment by liqul** [comment]
Check my answer here https://github.com/microsoft/TaskWeaver/issues/360
