### ISSUE TITLE
Experience and Planner examples are being ignored sometimes

### ISSUE THREAD

**Issue by GihanMora** [microsoft/TaskWeaver#364]
**Describe the bug**

I've added planner examples and experiences to guide certain behaviors in Task Weaver. For example, I use these to improve the following scenarios:

To avoid common errors - I leverage experiences here.
When dealing with complex queries that involve performing action A and action B, I split the question and send the parts separately to plugin A and plugin B, instead of sending the entire query to either plugin, which often results in errors or incomplete responses.
However, it sometimes doesn't behave as expected. Even when I provide the same queries in the experience or planner examples, it still makes mistakes. Is there a way to give more weight to the experience/planner examples?

**Environment Information**
 - OS:Windows
 - Python Version 3.11
 - LLM that you're using: GPT-4

**Comment by liqul** [comment]
I think the first step you can check is wether the examples and experience tips are loaded into the prompt. For this, you can go to `taskweaver/project/workspace/<pick_a_session_id>/planner_prompt_log_round-xxxx.json`. It is a json object and you can open it and search for key words in your custom examples or experience tips. 

Once you've make sure that they are correctly presented and it still does not function correctly, this becomes a more complex problem which typically involves careful prompt engineering efforts. For example, you can check if the plugin descriptions contain any instructions that may have caused this misunderstanding. 

A practical tip is that you can ask the agent why it does not follow your instructions (e.g., typing 'why you didn't split my query according to my instructions xxx?' and then check its answer to get any hints on why it behaves in that way. Sometimes, the agent will explain the reason that can give you some hints from the prompt. 

In general, this is more a prompt engineering issue that requires careful twisting in the wordings of various parts in the prompt.
