### ISSUE TITLE
[multi-project and multi-role] 

### ISSUE THREAD

**Issue by SHX9610** [microsoft/TaskWeaver#367]
hallo, 
I want to know,  Can I create **multiple sub-projects** and use them as roles? Then create a **main project** at the top level to schedule these sub-projects (roles)?

**Comment by liqul** [comment]
I don't think so...We don't support running a 'sub-project' as a role yet.

**Comment by SHX9610** [comment]
> I don't think so...We don't support running a 'sub-project' as a role yet.

hello,

       I have some confusion about your response:
            1)	As you said, the current project does not support running a ‘sub-project’ as roles, but is there any other way to achieve the function I mentioned? Maybe my understanding of project/planner/role is wrong.
            2)	If the current repo cannot achieve the functions I mentioned by running a sub-project as a role or through other methods, is it necessary to iterate on this as an issue later?

**Comment by SHX9610** [comment]
> I cann't see the scenario where you need to run a TaskWeaver project as a role, or maybe you can explain more about this.
> 
> If you indeed somehow need to do this, you can implement a new role to call TaskWeaver as a lib.


**I answer why I want to run a ‘sub-project’ as a role:**
        Currently there are three roles: King, Soldier, and Knight. 
        Therefore, the King can be used as a main project, and the Soldier and Knight can be used as sub-projects.
        ‘King project’ has ‘planner_examples’, and the ‘Soldier project’ and the ‘Knight project’ each have their own ‘planner_examples’
        The ‘planner_examples’ in the King project is responsible for planning the execution of the Soldier and Knight.
        The Soldier project and the Knight project are responsible for planning their own behavior.
     
As you said, for above the scenario, is it possible to implement a new role to call TaskWeaver as a lib?

**Comment by liqul** [comment]
My short answer is yes. But we haven't tried it before and I envision there are some efforts in bringing it up, just making sure each Taskweaver project has its own project directory.

**Comment by SHX9610** [comment]
> My short answer is yes. But we haven't tried it before and I envision there are some efforts in bringing it up, just making sure each Taskweaver project has its own project directory.

Thank you, have a nice day.
