### ISSUE TITLE
Exporting and importing experience

### ISSUE THREAD

**Issue by GihanMora** [microsoft/TaskWeaver#369]
Can we export and import the experiences between different TaskWeaver projects?
Can we manually add experiences to the projects?

**Comment by liqul** [comment]
Yes, you can copy the experiences from one project to another, if and only if they have different experience IDs.

You can also hand craft some experiences. They need to have the names of `handcrafted_exp_{exp_id}.yaml` and reside in the `project/experience` folder. Within each yaml file, you need to have two attributes like 

```yaml
exp_id: xxx
experience_text: xxx
```

**Comment by GihanMora** [comment]
So, if I am copying experiences from one project to another, what are the steps?. 
I copied project/experience and enabled experiences using the config file. But how does it extend the planner prompt of the new taskweaver project? 
is there a command to issue? like the one we got for refreshing plugins?

**Comment by liqul** [comment]
Refering to the doc:
```
To enable the experience feature, you only need to set the planner.use_experience and/or code_generator.use_experience parameter in the configuration file to true.
```
When TaskWeaver starts, it will automatically check if there are experience tips under that folder. If yes, the planner will load 
them accordingly. You can check in the logs if there is something looks like

```
Experience loaded successfully, xxxxx
```
