### ISSUE TITLE
Choose different roles according to needs

### ISSUE THREAD

**Issue by SHX9610** [microsoft/TaskWeaver#374]
Hello,
The following is the implementation section of ’planner_examples yaml‘. Can we implement different modules/roles that planners can choose to enter based on user descriptions？

- message: Successfully obtain user response. If the user reply A, then go to the A-M module. If the user reply B, then go to the B-M module.
  send_from: User
  send_to: Planner
  attachment_list:
- message: xxxxxxxxxx
  send_from: Planner
  send_to: A-M
  attachment_list:
- message: xxxxxxxxx
  send_from: Planner
  send_to: B-M
  attachment_list:

**Comment by liqul** [comment]
Yes, there is an example here https://github.com/microsoft/TaskWeaver/blob/main/project/planner_examples/example-planner-echo.yaml

**Comment by SHX9610** [comment]
> Yes, there is an example here https://github.com/microsoft/TaskWeaver/blob/main/project/planner_examples/example-planner-echo.yaml


I don't think your example is consistent with the scenario I mentioned.
My scene requires selecting/skipping some roles.

first, **User -> planner**
then, **planner sent to A-M or B-M** base on user input.

If the user reply A, then go to the A-M module, and skip B-M module
If the user reply B, then go to the B-M module, and skip A-M module

**Comment by liqul** [comment]
I was not saying the example can solve your problem. I mean that you could refer to that to write your own example.
