### ISSUE TITLE
could i load a historical session in worksapce?

### ISSUE THREAD

**Issue by olddriver112233** [microsoft/TaskWeaver#375]
**I want to load a historical session maybe i created it  two days ago, but i don't know how to do  **
maybe like this 

![屏幕截图 2024-06-28 113015](https://github.com/microsoft/TaskWeaver/assets/40563411/128e6796-0ef4-425b-886a-39cac59dea4d)

**Comment by liqul** [comment]
I think you are asking the question in a wrong place. This is not for chatgpt related issues.

**Comment by olddriver112233** [comment]
> I think you are asking the question in a wrong place. This is not for chatgpt related issues.

I want to ask if the project includes a feature for managing historical sessions？

**Comment by liqul** [comment]
This is not supported yet.
