### ISSUE TITLE
How to access the attachment of type image/PDF in a new role

### ISSUE THREAD

**Issue by arhaang13** [microsoft/TaskWeaver#383]
I am trying to create a new role and I want to access the attachment either generated by the code that is a plot or a graph or i want to access the attachment uploaded by the user. 

How will I be able to access this attachment in the role. 
Is there an url or a method to get the attachment?

Thank you!

**Comment by arhaang13** [comment]
I got how to get the image using get_attachment. but i want to parse the url of a base64 image to the openai api. 
but I get a bad request error. 

Kindly help!

**Comment by liqul** [comment]
> I am trying to create a new role and I want to access the attachment either generated by the code that is a plot or a graph or i want to access the attachment uploaded by the user.
> 
> How will I be able to access this attachment in the role. Is there an url or a method to get the attachment?
> 
> Thank you!

There's no such API. If you need to access the artifact generated by role A from role B, you need somehow pass the path in the message to it.
