### ISSUE TITLE
when using TaskWeaver as a library, how to output log

### ISSUE THREAD

**Issue by SHX9610** [microsoft/TaskWeaver#386]
when using TaskWeaver as a library, how to output intermediate logs (planner's planning process, etc.) like the intermediate process displayed in the front-end UI

**Comment by liqul** [comment]
If you look at the response (like [here](https://microsoft.github.io/TaskWeaver/docs/usage/library)), it contains all the information generated by the planner. 

So, I think you are asking if there is something like the `stream` mode, where the output is streamed to the client piece by piece. If this is the case, we do not support directly yet, but you can take a look at this [thread](https://github.com/microsoft/TaskWeaver/issues/371).
