### ISSUE TITLE
Transitioning from OpenAI API Keys to Azure Managed Identity (MSI) – Issues with Taskweaver Expecting API Keys in Multiple Processes

### ISSUE THREAD

**Issue by bsavocad** [microsoft/TaskWeaver#408]
Hello,

I'm currently in the process of transitioning my application from using OpenAI API keys to Azure Managed Service Identity (MSI) for enhanced security and credential management. However, I'm encountering several issues with Taskweaver, mainly because it expects an API key in multiple processes.

_Issues Encountered:_

- API Key Dependency: Taskweaver seems to require an explicit OpenAI API key across various processes, and there doesn't appear to be an out-of-the-box way to configure it to use Azure MSI for authentication.
- Multiple Process Configuration: The need to supply the API key in multiple places makes the transition to MSI challenging, as MSI abstracts away the need for explicit keys.

_Questions:_

- Has anyone successfully configured Taskweaver to work with Azure MSI instead of traditional API keys?
- Are there any guidelines or best practices available for integrating Taskweaver with Azure MSI?
- Can anyone share their findings or experiences in setting this up?

_What I've Tried So Far:_

- Configuration Attempts: I've attempted to modify the Taskweaver configuration to leverage MSI, but I keep running into authentication issues.
- Documentation Review: I've reviewed the Taskweaver documentation and existing GitHub issues but haven't found relevant information regarding MSI integration.
- Community Search: Searched online forums and communities for insights but haven't found a solution.

_Additional Information:_

- Error Messages: Happy to provide specific error logs if needed.
- Code Samples: Can share snippets of how I've attempted to configure MSI with Taskweaver.

Request:

Any assistance or guidance on how to overcome these issues would be greatly appreciated. If MSI integration isn't currently supported, are there any workarounds or plans to support this in the future?

Thank you for your help!

**Comment by Jack-Q** [comment]
We support using Entra authentication when using Azure OpenAI on Azure services. Maybe you can check the related instructions in [this doc](https://microsoft.github.io/TaskWeaver/docs/llms/aoai#using-entra-authentication) to configure access Azure OpenAI with managed identity.

**Comment by bsavocad** [comment]
unfortunately, i have not been able to solve this problem even though i followed the documentation to the letter. i keep getting errors like _**ValueError: Config value llm.azure_ad.aad_client_secret**_ is not found, when variables like these shouldn't be hardcoded but should auto-execute with DefaultAzureCredential by defining my managed_identity_client_id and my default_credential for my token_provider. have you heard of similar issues? it's quite frustrating!

**Comment by Jack-Q** [comment]
Please be sure the use the latest version of code from the repo. If the error still occurs, could you share your configuration and the detailed error message here?

**Comment by bsavocad** [comment]
The solution we found involves creating a function to generate the token and including it in the OpenAI.py file. This way, we are able to execute the token generation remotely without needing the presence of an API key. If you have any questions, feel free to reach out to us.
