### ISSUE TITLE
Issue when trying to enable tracing

### ISSUE THREAD

**Issue by dasuni1999** [microsoft/TaskWeaver#416]
Hi,
When I add the following piece of code in the taskweaver_config.json file:
    "tracing.enabled": true,
    "tracing.exporter": "otlp",
    "tracing.endpoint": "http://127.0.0.1:4317",
    "tracing.tokenizer_target_model": "gpt-4"

I'm getting the following error. 

.ConnectTimeout: HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /encodings/cl100k_base.tiktoken 
![image](https://github.com/user-attachments/assets/54ad09fc-4205-4685-8853-a38b37d2ec5b)

Can someone suggest a reason for this error to occur?

**Comment by liqul** [comment]
It seems the tokenizer, i.e., tiktoken, failed to download its configuration file. Can you make sure that you environment has no problem of internet access?

**Comment by dasuni1999** [comment]
I did have a problem of accessing the internet to download the tiktoken encoding dictionary. So I downloaded it locally for tiktoken to use. Found this link helpful" https://stackoverflow.com/questions/76106366/how-to-use-tiktoken-in-offline-mode-computer
