### ISSUE TITLE
documentation correction for entra ID

### ISSUE THREAD

**Issue by simra** [microsoft/TaskWeaver#425]
**Describe the bug**
The documents at https://microsoft.github.io/TaskWeaver/docs/llms/aoai are incorrect for authentication using Entra ID.

The current documents indicate this configuration setting:
```
"llm.auth_mode":"default_azure_credential",
```
which throws an exception.  The correct setting is 
```
"llm.azure_ad.aad_auth_mode":"default_azure_credential",
```

**Environment Information (please complete the following information):**
 - OS: WSL
 - Python Version 3.11
 - LLM that you're using: gpt-4o
 - Other Configurations except the LLM api/key related: all other settings as indicated in the Entra auth docs. I was able to verify that the corrected configuration runs successfully for my endpoint.

**Comment by liqul** [comment]
Thanks for raising this issue, and it has been fixed.

**Comment by liqul** [comment]
Close as it has been fixed.
