### ISSUE TITLE
Allow to install any python package

### ISSUE THREAD

**Issue by sagarspatil** [microsoft/TaskWeaver#6]
Is there a way to enable TaskWeaver to autonomously install any Python package it requires, rather than restricting it to the ones pre-defined in `code_verification.allowed_modules`?

Currently, predicting the exact packages TaskWeaver might need for a given task can be challenging. This limitation significantly narrows the tool's practical utility. By allowing more flexibility in package installation, TaskWeaver's adaptability and effectiveness could be substantially improved.

**Comment by zhangxu0307** [comment]
Hi, @sagarspatil ! Thanks for your interests for TaskWeaver! You can try to disable the code verification module by setting `code_verification.code_verification_on` to false, enabling arbitrary Python package installation and usage.

**Comment by tahsinalamin** [comment]
@gdssingh7 did you find any solution? I'm having the same issue.
