### ISSUE TITLE
Add a Critic role

### ISSUE THREAD

**Issue by dcieslak19973** [microsoft/TaskWeaver#66]
**Is your feature request related to a problem? Please describe.**
Having dabbled in TaskWeaver and AutoGen, I think that AutoGen's use of a "Critic" agent which weighs in on both plans and code can frequently improve the agent's overall ability to satisfy a user request.

**Describe the solution you'd like**
Add an additional role of Critic w/in TaskWeaver.  The critic would review both Plans and Code before those roles passed them along.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by zhangxu0307** [comment]
We added the self-correction mechanism for both Planner and CodeInterpreter but not sperated it as an indiviual role.
