### ISSUE TITLE
Works fine on Windows Docker

### ISSUE THREAD

**Issue by Alblahm** [microsoft/TaskWeaver#7]
It works as it is in Windows dockerized container

 **If you add this dockerfile to the TaskWeaver folder:**

```
# basic setup
FROM python:3.10
RUN apt-get update && apt-get -y update
RUN apt-get install -y sudo git npm

# Setup user to not run as root
RUN adduser --disabled-password --gecos '' taskweaver-dev
RUN adduser taskweaver-dev sudo
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
USER taskweaver-dev

# Pull repo
RUN cd /home/taskweaver-dev && git clone https://github.com/microsoft/TaskWeaver.git
WORKDIR /home/taskweaver-dev/TaskWeaver

# Install TaskWeaver (Note: extra components can be installed if needed)
RUN sudo pip install -r requirements.txt

# override default image starting point
CMD /bin/bash
ENTRYPOINT []
```

**Then create the image with:**
`docker build -t taskweaver .`

Edit the "TaskWeaver\project\taskweaver_config.json" to add your api key and ...

**Then change to the program folder in a command console and run the container with:**
set "RutaTaskWeaver=%cd%"
`docker run -v %RutaTaskWeaver%:/home/taskweaver-dev/TaskWeaver --rm -it taskweaver`

 This mounts the local windows directory inside the docker container, so you can read or change the temp files from your windows browser.

**Comment by ShilinHe** [comment]
Thanks for providing the dockerfile, we have marked it as an enhancement on our plan.
