### ISSUE TITLE
Question on planner example

### ISSUE THREAD

**Issue by antoan** [microsoft/TaskWeaver#75]
I'd like to better understand how to author my own examples and was unsure how to  interpret the attachment_list elements in https://github.com/microsoft/TaskWeaver/blob/main/project/planner_examples/example-planner.yaml:
```

- message: Please load the data file /home/data.csv and count the rows of the loaded data
        send_from: Planner
        send_to: CodeInterpreter
        attachment_list:
        **- type: init_plan
          content: |-
                1. load the data file
                2. count the rows of the loaded data <sequentially depends on 1>
                3. report the result to the user <interactively depends on 2>
        - type: plan
          content: |-
            1. instruct CodeInterpreter to load the data file and count the rows of the loaded data
            2. report the result to the user
        - type: current_plan_step**
          content: 1. instruct CodeInterpreter to load the data file and count the rows of the loaded data
      - message: Load the data file /home/data.csv successfully and there are 100 rows in the data file
        send_from: CodeInterpreter
```
Is the attachment list intended to indicate the current state of the planner: full initial plan (init_plan), remaining steps (plan) in the overall plan and the current step (current_step, to be included in every message from the planner?

**Comment by zhangxu0307** [comment]
Hi, @antoan ! Thanks for your question. 
1. If you want to create your own example for Planner, you can refer to https://github.com/microsoft/TaskWeaver/blob/main/docs/example.md 
2. `attachment_list` fields for Planner:
a. `init_plan`: We require Planner to create a comprehensive draft plan, breaking down tasks into smaller components as much as possible.
b. `plan`: We prompt the Planner to consolidate several steps of the initial plan, particularly those with a sequential dependency, and present the final version of the plan. More details can be referred to Sec.4.4 in our [paper](https://export.arxiv.org/pdf/2311.17541).
c. `current_step`: The ongoing step being executed by Planner.
