### ISSUE TITLE
compatibility issue error on pyautogen and other packages

### ISSUE THREAD

**Issue by amitlals** [microsoft/TaskWeaver#81]
Team, We should add pre-steps to create conda or .venv to avoid the error below, just a suggestion! 

Installing collected packages: openai
  Attempting uninstall: openai
    Found existing installation: openai 0.28.1
    Uninstalling openai-0.28.1:
      Successfully uninstalled openai-0.28.1
**ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behavior is the source of the following dependency conflicts.**
pyautogen 0.1.14 requires openai<1, but you have openai 1.5.0 which is incompatible.
Successfully installed openai-1.5.0

![image](https://github.com/microsoft/TaskWeaver/assets/37605691/e4512548-223a-4a49-8195-4dce4f754401)

**Comment by liqul** [comment]
@amitlals Thanks for the suggestion. Will add steps of creating a conda env. 

W.r.t this specific error in your screen shot, the openai api has a breaking update from 0.x to 1.x, that causes this issue. I believe all packages will upgrade to this stable version shortly.
