### ISSUE TITLE
Request -Quality examples for creating Python plugins?

### ISSUE THREAD

**Issue by amitlals** [microsoft/TaskWeaver#82]
**Is your feature request related to a problem? Please describe.**
Feature request - Add few sample plug-ins esp. connecting with databases

**Describe the solution you'd like**
We want to leverage TW scenario, where we able to connect SQL or oracle DB in realtime using plugin to fetch required content

```[tasklist]
### Tasks
```

**Comment by liqul** [comment]
@amitlals We have a plugin `sql_pull_data` for querying sqlite3 which could be used as an entry point for making complicated plugins for other sql dbs. Could you specify your concrete requirements that are not covered in our sample plugin?

**Comment by AR-BABER** [comment]
i have kind of a same task, all i need is a guideline to accomplish it like should i change planner add edit existing one? my task is for it to connect with postgres database and fetch data and on that data apply certain operations depending upon the query? how would i got about it?

**Comment by amitlals** [comment]
> @amitlals We have a plugin `sql_pull_data` for querying sqlite3 which could be used as an entry point for making complicated plugins for other sql dbs. Could you specify your concrete requirements that are not covered in our sample plugin?

Yes, I'm building a HANA DB plugin for a quick demo, it seems it's not getting register and trying to hit sql_pull_data plugin again and again; 
I can share my HANA Plugin code as well , if required. 

Question - Do we really required to manually register new plugin; Though I'm creating this new plugin in same plugin dir only using @plugin syntax. 

Any inputs are highly appreciated. 

![image](https://github.com/microsoft/TaskWeaver/assets/37605691/406c4227-0e45-42cc-bb8d-20bf09e9b381)


![image](https://github.com/microsoft/TaskWeaver/assets/37605691/f302cdaa-74b9-4487-aee7-94c81f40644d)

**Comment by liqul** [comment]
Some suggestions: 
1. first make sure the schema is correct and `enabled: true` in the yaml file. Please go through this doc if you haven't https://microsoft.github.io/TaskWeaver/docs/plugin/plugin_intro
2. if the existing plugins not useful, please delete them (or move them out of the plugin folder) to make it easier for the model to choose the right plugin

@AR-BABER I don't think you need to modify the planner or the code interpreter if you only need to pull data from a postgresql db. The plugins in the project are samples to follow if you want to make your own. But overall, it is quite flexible. You can view each plugin as a python function and it is free to implement any logic inside it. 

Our current `sql_pull_data` plugin is based on langchain which provides a set of tools to interact with various databases. Checkout the langchain documents (e.g., https://python.langchain.com/docs/use_cases/qa_structured/sql) to learn more about handling database related tasks.

**Comment by amitlals** [comment]
> Some suggestions:
> 
> 1. first make sure the schema is correct and `enabled: true` in the yaml file. Please go through this doc if you haven't https://microsoft.github.io/TaskWeaver/docs/plugin/plugin_intro
> 2. if the existing plugins not useful, please delete them (or move them out of the plugin folder) to make it easier for the model to choose the right plugin
> 
> @AR-BABER I don't think you need to modify the planner or the code interpreter if you only need to pull data from a postgresql db. The plugins in the project are samples to follow if you want to make your own. But overall, it is quite flexible. You can view each plugin as a python function and it is free to implement any logic inside it.
> 
> Our current `sql_pull_data` plugin is based on langchain which provides a set of tools to interact with various databases. Checkout the langchain documents (e.g., https://python.langchain.com/docs/use_cases/qa_structured/sql) to learn more about handling database related tasks.

Thanks for your inputs.

I removed the existing SQL plugin to see if my HANA DB plugin works...sounds like it's not able to detect this plugin? any idea?

![image](https://github.com/microsoft/TaskWeaver/assets/37605691/d8c6730f-917e-4007-9bf5-49945d0a1887)

**Comment by AR-BABER** [comment]
![Screenshot 2023-12-23 010321](https://github.com/microsoft/TaskWeaver/assets/84210776/342f5882-bff3-4a5a-a435-fb0e0bdd0092)


i have the same issue, i followed the exact schema for sql pull data to form my own plugin to pull data from local postgress database, made the necessary changes, but this is happening. i think it fails to run the new plugin i dont know why, and after failure it start creating its own code.

**Comment by amitlals** [comment]
YES!!! It appears we're facing a similar situation. It seems like we might be overlooking a step in **registering** a new plugin with TaskWeaver. It's as if it's hardcoded to work with standard plugins only. We need a solution, else I'll drop this project for customer demo.

**Comment by liqul** [comment]
@amitlals and @AR-BABER  without reading your yaml files, I cannot make sure what has caused this issue. It is not hardcoded. Could you please attach your plugin schemas so that we can diagnose what happened?

**Comment by liqul** [comment]
@amitlals @AR-BABER we also find youtube videos demonstrating how to create custom plugins, please check if they could help
https://www.youtube.com/watch?v=o4zmEEKvdTY

**Comment by amitlals** [comment]
> @amitlals and @AR-BABER without reading your yaml files, I cannot make sure what has caused this issue. It is not hardcoded. Could you please attach your plugin schemas so that we can diagnose what happened?

Thanks for your response. I'm sharing my yaml file for your review. 
[name hana_pull_data_template.txt](https://github.com/microsoft/TaskWeaver/files/13763573/name.hana_pull_data_template.txt)

**Comment by amitlals** [comment]
> @amitlals @AR-BABER we also find youtube videos demonstrating how to create custom plugins, please check if they could help https://www.youtube.com/watch?v=o4zmEEKvdTY

Yes, I saw this link earlier before I drafted my plugin. Thanks!!

**Comment by liqul** [comment]
> > @amitlals and @AR-BABER without reading your yaml files, I cannot make sure what has caused this issue. It is not hardcoded. Could you please attach your plugin schemas so that we can diagnose what happened?
> 
> Thanks for your response. I'm sharing my yaml file for your review. [name hana_pull_data_template.txt](https://github.com/microsoft/TaskWeaver/files/13763573/name.hana_pull_data_template.txt)

Is this the complete schema file? I didn't see the `parameters` and `returns`, so this is invalid.

**Comment by amitlals** [comment]
> > > @amitlals and @AR-BABER without reading your yaml files, I cannot make sure what has caused this issue. It is not hardcoded. Could you please attach your plugin schemas so that we can diagnose what happened?
> > 
> > 
> > Thanks for your response. I'm sharing my yaml file for your review. [name hana_pull_data_template.txt](https://github.com/microsoft/TaskWeaver/files/13763573/name.hana_pull_data_template.txt)
> 
> Is this the complete schema file? I didn't see the `parameters` and `returns`, so this is invalid.

Sorry, Here is the complete file


hana_pull_data.ymal  >>
name: hana_pull_data
enabled: true
required: false
description: Pull data from SAP HANA database using SQL queries from specific database table ZDEMO_SOI. 
  This plugin takes user requests when obtaining data from database is explicitly mentioned. 
  Otherwise, confirm with the user if they want to pull data from this database table or any other known table. 
  The data from this database can only used for technical analysis and creating forecasting models with diagrams.

parameters:
  - name: query
    type: str
    required: true
    description: >-
      This is the query in natural language that the user wants to get data from database.
      If any specific column or value is mentioned, make sure to include them in the query, 
      exactly in the right format or form.

returns:
  - name: df
    type: pandas.DataFrame
    description: This is the dataframe containing the data from the database.
  - name: description
    type: str
    description: This is a string describing the data pulled from the database.

configurations:
  hana_host:  "xxx.xxx.xxx"
  hana_port:  "30215"
  hana_user: "saphana"
  hana_password: "xxxxx"
  api_type: openai
  api_base: https://api.openai.com
  api_key: 
  deployment_name: test

**Comment by liqul** [comment]
Still cannot find your plugin？I'm using exactly the same configures as you. 
![image](https://github.com/microsoft/TaskWeaver/assets/7489260/7f08f32f-24ad-457b-a329-dd7f77a2d4cb)
![image](https://github.com/microsoft/TaskWeaver/assets/7489260/16f5dbeb-1505-41e8-9a62-738e4d0b8fa2)

**Comment by amitlals** [comment]
> Still cannot find your plugin？I'm using exactly the same configures as you. ![image](https://private-user-images.githubusercontent.com/7489260/292708571-7f08f32f-24ad-457b-a329-dd7f77a2d4cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0Nzg0MDYsIm5iZiI6MTcwMzQ3ODEwNiwicGF0aCI6Ii83NDg5MjYwLzI5MjcwODU3MS03ZjA4ZjMyZi0yNGFkLTQ1N2ItYTMyOS1kZDdmNzdhMmQ0Y2IucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjVUMDQyMTQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDExZDhhOTQ3NTRmODEwY2FlZjM1MzdkZjQ1MjVkNDQ2MTcxZTg0MmZkODU0MzhiYmJiMzk3YTYwODlhMWJiMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.v8d3VWSLbN_R7n5oPy8xjRUjwvQWdT4-PL1MZOoWWxk) ![image](https://private-user-images.githubusercontent.com/7489260/292708595-16f5dbeb-1505-41e8-9a62-738e4d0b8fa2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0Nzg0MDYsIm5iZiI6MTcwMzQ3ODEwNiwicGF0aCI6Ii83NDg5MjYwLzI5MjcwODU5NS0xNmY1ZGJlYi0xNTA1LTQxZTgtOWE2Mi03MzhlNGQwYjhmYTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjVUMDQyMTQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzBjZGRhY2JjYmI4NDhkNGE0MDlkMjlkODIwZTRmNWZhOTk4OTdkNjUzMTllODQ0N2VkYThiNjgzYzFhYWFkOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.hcE4g4E_mOtTuw7_GNWlaXoTlu6pbG_v2mDj6Z6Z7cQ)

I think still not available...see the detailed error coming up on this plugin name only.

![image](https://github.com/microsoft/TaskWeaver/assets/37605691/41100b0a-7bdf-4769-8cfa-2a43a06f7b11)

**Comment by liqul** [comment]
The model already finds your plugin (see the generated code calling your plugin). Now, the problem should come from your implementation. You can see the error saying no module named 'hdbcli'. So, this is the root cause.

**Comment by amitlals** [comment]
> The model already finds your plugin (see the generated code calling your plugin). Now, the problem should come from your implementation. You can see the error saying no module named 'hdbcli'. So, this is the root cause.

Thanks!! I did installed this package. I'm getting strange error now --

Error: Cannot process your request due to Exception: 'ascii' codec can't encode character '\xd7' in position 25: ordinal not in range(128)

![image](https://github.com/microsoft/TaskWeaver/assets/37605691/c5e97ac7-0108-4f07-a33e-321c77f93a2d)

**Comment by liqul** [comment]
Is this a persistent issue?

**Comment by amitlals** [comment]
> Is this a persistent issue?

I've reconstructed the environment twice, yet this ascii issue keeps occurring regularly.

**Comment by liqul** [comment]
Have you succeeded in calling other plugins? This behavior seems inconsistent with your previous screenshots where the planner can successfully generate a plan. In your new screenshots, it seems the LLM calls are failing due to some encoding errors.

**Comment by amitlals** [comment]
Yes! Other plugins worked without any issues. This new one is causing issues a lot. Now this new trouble of acsii needs to be reviewed...seems python version is having some compatibility issues.

**Comment by liqul** [comment]
I suggest you first implement a dummy plugin, for example, just returning a static string. Until the end to end path has been gone through, then add more logic to the implementation.

**Comment by AR-BABER** [comment]
I was able to run the plugin. Thanks

**Comment by amitlals** [comment]
My HANA DB plugin is a go! Closing this issue and adding it to my technical article. Thanks!! @liqul 

Cheers! appreciate your help! 

![image](https://github.com/microsoft/TaskWeaver/assets/37605691/6bd18bcb-d384-4f65-b491-4e7dc8ad57fa)

**Comment by AR-BABER** [comment]
> My HANA DB plugin is a go! Closing this issue and adding it to my technical article. Thanks!! @liqul
> 
> Cheers! appreciate your help!
> 
> ![image](https://private-user-images.githubusercontent.com/37605691/292961848-6bd18bcb-d384-4f65-b491-4e7dc8ad57fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3MTYwOTIsIm5iZiI6MTcwMzcxNTc5MiwicGF0aCI6Ii8zNzYwNTY5MS8yOTI5NjE4NDgtNmJkMThiY2ItZDM4NC00ZjY1LWI0OTEtNGU3ZGM4YWQ1N2ZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI3VDIyMjMxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiOTgzMDI4MzI5NGQ4YjY0YTcxMjliZTYzYmMzNmZkNWUxNmE0MTE4OTY1M2Y4OTA4OWI4NGY1NjU1MzRiODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IPGvbRPrkszLJrifAl4Nshjzf6Hu1XFUUehqO17ejcY)

Please do share your experience and what you achieved...
