### ISSUE TITLE
Trying to create plugin using Dynamics Marketing all the data tables with Dataverse. 

### ISSUE THREAD

**Issue by jackiemakhija** [microsoft/TaskWeaver#89]
**Describe the solution you'd like**

I am planning to develop a plugin for Dynamics Marketing that directly accesses Dataverse data tables, allowing seamless integration and data use across all Dynamics 365 modules. This will enhance data management and efficiency in Dynamics Marketing and other Dynamics 365 areas.

Do you have template plugin to leverage this functionality???

**Comment by ShilinHe** [comment]
Hi, if you want to develop a new plugin, please refer to the sample plugins in the folder project/plugins and [documents on how to develop a new plugin](https://microsoft.github.io/TaskWeaver/docs/plugin/how_to_develop_a_new_plugin). 
For the specific requests of accessing Dataverse, you may implement it in Python by the following reference:
[blog](https://andyhowes.co/easily-connect-to-dataverse-microsoft-dynamics-with-python/)
[forum](https://powerusers.microsoft.com/t5/Microsoft-Dataverse/Python-Connectivity-with-Microsoft-Dataverse-CDS/td-p/1353220)
