### ISSUE TITLE
[FEATURE REQUEST] On Playground Ui show conversation history like chatgpt 

### ISSUE THREAD

**Issue by rrfaria** [microsoft/TaskWeaver#99]
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

The Playground UI could feature a chat history containing all messages sent to the AI, including tasks and associated details for future reference. This information could be stored in an SQLite database or any other suitable database system. Implementing a vector store might enhance search speed for future queries.

**Comment by ShilinHe** [comment]
Thanks for your suggestion! Currently the UI frontend (developed with chainlit) does not support the chat history display. We will leave it as future work.
